import { useState, useEffect, useCallback, useMemo, useRef } from "react";
// ═══════════════════════════════════════════════════════════════
// NASAB v6.0 — Jaga Nasabmu
// Full SaaS Family Tree + NIK Intelligence + Faraidh
// ═══════════════════════════════════════════════════════════════
const APP={name:"NASAB",tag:"Jaga Nasabmu",ver:"6.0"};
const SK="nasab-v6";
// Card sizing — Hybrid avatar layout
const CW=176,CH=120;        // Card width/height
const GX=44,GY=148;         // Horizontal/vertical gap
const CG=18;                // Couple gap
const AVATAR_R=24;          // Avatar radius (48px diameter)
const ACCENT_H=3;           // Top accent bar height
const VW={CANVAS:"canvas",MAP:"map",LIST:"list",STATS:"stats",TL:"timeline",INS:"insights",WARIS:"waris"};
const RL={O:"owner",E:"editor",V:"viewer"};
const GL=[{l:"Kakek/Nenek",i:"👴"},{l:"Ayah/Ibu",i:"👨‍👩‍👧‍👦"},{l:"Anak",i:"🧒"},{l:"Cucu",i:"👶"},{l:"Cicit",i:"🌱"},{l:"Canggah",i:"🌿"}];
const GC=["#14b8a6","#6366f1","#f59e0b","#ec4899","#8b5cf6","#f97316"];
// ─── NIK PROVINCE MAP ────────────────────────────────────────
const PROV={"11":"Aceh","12":"Sumatera Utara","13":"Sumatera Barat","14":"Riau","15":"Jambi","16":"Sumatera Selatan","17":"Bengkulu","18":"Lampung","19":"Kep. Bangka Belitung","21":"Kep. Riau","31":"DKI Jakarta","32":"Jawa Barat","33":"Jawa Tengah","34":"DI Yogyakarta","35":"Jawa Timur","36":"Banten","51":"Bali","52":"NTB","53":"NTT","61":"Kalimantan Barat","62":"Kalimantan Tengah","63":"Kalimantan Selatan","64":"Kalimantan Timur","65":"Kalimantan Utara","71":"Sulawesi Utara","72":"Sulawesi Tengah","73":"Sulawesi Selatan","74":"Sulawesi Tenggara","75":"Gorontalo","76":"Sulawesi Barat","81":"Maluku","82":"Maluku Utara","91":"Papua Barat","92":"Papua"};
const PROV_COORDS={"11":[4.7,-96.7],"12":[2.5,99.0],"13":[-0.9,100.4],"14":[0.5,101.4],"15":[-1.6,103.6],"16":[-3.3,104.7],"17":[-3.8,102.3],"18":[-5.0,105.0],"19":[-2.7,106.6],"21":[1.0,104.5],"31":[-6.2,106.8],"32":[-6.9,107.6],"33":[-7.15,110.4],"34":[-7.8,110.4],"35":[-7.5,112.7],"36":[-6.4,106.1],"51":[-8.4,115.2],"52":[-8.6,117.4],"53":[-8.7,121.0],"61":[-0.3,111.5],"62":[-1.7,113.4],"63":[-3.1,115.4],"64":[-0.5,117.1],"65":[2.7,117.5],"71":[1.5,124.8],"72":[-1.4,121.4],"73":[-3.7,119.4],"74":[-4.0,122.5],"75":[0.6,122.4],"76":[-2.8,119.2],"81":[-3.2,130.1],"82":[1.6,127.8],"91":[-1.3,132.3],"92":[-4.0,138.5]};
// ─── NIK ENGINE ──────────────────────────────────────────────
const NIK={
  parse(nik){
    const s=nik.replace(/\D/g,"");
    if(s.length!==16)return{valid:false,error:"NIK harus 16 digit"};
    const provCode=s.slice(0,2),kabCode=s.slice(0,4),kecCode=s.slice(0,6);
    const dd=parseInt(s.slice(6,8)),mm=parseInt(s.slice(8,10)),yy=parseInt(s.slice(10,12));
    const isFemale=dd>40;const day=isFemale?dd-40:dd;
    if(day<1||day>31||mm<1||mm>12)return{valid:false,error:"Tanggal lahir tidak valid"};
    const prov=PROV[provCode];
    if(!prov)return{valid:false,error:`Kode provinsi ${provCode} tidak dikenali`};
    const year=yy>50?1900+yy:2000+yy;
    const birthDate=`${year}-${String(mm).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
    const gender=isFemale?"female":"male";
    const coords=PROV_COORDS[provCode]||null;
    return{valid:true,nik:s,provinsi:prov,provCode,kabCode,kecCode,birthDate,gender,day,month:mm,year,coords,masked:`${s.slice(0,6)}••••••${s.slice(12)}`};
  },
  mask(nik){const s=(nik||"").replace(/\D/g,"");return s.length===16?`${s.slice(0,6)}••••••${s.slice(12)}`:nik||"";},
  validate(nik){return NIK.parse(nik).valid;}
};
// ─── DB ──────────────────────────────────────────────────────
const DB={
  async g(k){try{const r=await window.storage.get(`${SK}:${k}`);return r?JSON.parse(r.value):null}catch{return null}},
  async s(k,v){try{await window.storage.set(`${SK}:${k}`,JSON.stringify(v))}catch{}},
  async d(k){try{await window.storage.delete(`${SK}:${k}`)}catch{}},
  async getUser(uid){return this.g(`u:${uid}`)},async setUser(u){return this.s(`u:${u.id}`,u)},
  async getUserByEmail(e){const idx=await this.g("idx:em")||{};const uid=idx[e.toLowerCase()];return uid?this.getUser(uid):null},
  async createUser({name,email,password}){const id=`u_${Date.now().toString(36)}`;const u={id,name,email:email.toLowerCase(),password,createdAt:new Date().toISOString(),families:[]};await this.setUser(u);const idx=await this.g("idx:em")||{};idx[email.toLowerCase()]=id;await this.s("idx:em",idx);return u},
  async getFamily(fid){return this.g(`f:${fid}`)},async setFamily(f){return this.s(`f:${f.id}`,f)},
  async createFamily({name,description,ownerId,ownerName}){const id=`f_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,5)}`;const f={id,name,description,ownerId,members:[],positions:{},invites:[],stories:[],collaborators:[{userId:ownerId,name:ownerName,role:RL.O}],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await this.setFamily(f);const u=await this.getUser(ownerId);if(u){u.families.push({id,name,role:RL.O});await this.setUser(u)}return f},
};
// ─── FAMILY ENGINE ───────────────────────────────────────────
const FE={
  ch:(pp,pid)=>pp.filter(p=>p.parentId===pid),
  sp:(pp,p)=>p.spouseId?pp.find(x=>x.id===p.spouseId)||null:null,
  pa:(pp,p)=>p.parentId?pp.find(x=>x.id===p.parentId)||null:null,
  sib:(pp,p)=>p.parentId?pp.filter(x=>x.parentId===p.parentId&&x.id!==p.id):[],
  gen:(pp,pid,g=0)=>{const p=pp.find(x=>x.id===pid);return(!p||!p.parentId)?g:FE.gen(pp,p.parentId,g+1)},
  desc:(pp,pid)=>{const c=FE.ch(pp,pid);return c.reduce((s,x)=>s+1+FE.desc(pp,x.id),0)},
  age:(p)=>{if(!p.birthDate)return null;const b=new Date(p.birthDate),e=p.deathDate?new Date(p.deathDate):new Date();let a=e.getFullYear()-b.getFullYear();if(e.getMonth()<b.getMonth()||(e.getMonth()===b.getMonth()&&e.getDate()<b.getDate()))a--;return a},
  stats:(pp)=>{const t=pp.length,m=pp.filter(p=>p.gender==="male").length;const mg=Math.max(0,...pp.map(p=>FE.gen(pp,p.id)));const pr=pp.filter(p=>FE.ch(pp,p.id).length>0);const ac=pr.length?(pr.reduce((s,p)=>s+FE.ch(pp,p.id).length,0)/pr.length).toFixed(1):0;return{total:t,males:m,females:t-m,living:pp.filter(p=>!p.deathDate).length,deceased:pp.filter(p=>p.deathDate).length,generations:mg+1,avgChildren:ac,geotagged:pp.filter(p=>p.location?.lat).length,nikCount:pp.filter(p=>p.nik).length}},
  search:(pp,q)=>{const s=q.toLowerCase().trim();return!s?pp:pp.filter(p=>p.name.toLowerCase().includes(s)||(p.birthPlace||"").toLowerCase().includes(s)||(p.notes||"").toLowerCase().includes(s))},
  findRel(pp,fid,tid){if(fid===tid)return{path:[],label:"Diri sendiri"};const adj={};pp.forEach(p=>{adj[p.id]=[]});pp.forEach(p=>{if(p.parentId&&adj[p.parentId]){adj[p.id].push({id:p.parentId,rel:"parent"});adj[p.parentId].push({id:p.id,rel:"child"})}if(p.spouseId&&adj[p.spouseId])adj[p.id].push({id:p.spouseId,rel:"spouse"})});const vis=new Set([fid]),q2=[{id:fid,path:[]}];while(q2.length){const{id,path}=q2.shift();for(const e of(adj[id]||[])){if(vis.has(e.id))continue;vis.add(e.id);const np=[...path,{id:e.id,rel:e.rel}];if(e.id===tid)return{path:np,label:FE._dr(np)};q2.push({id:e.id,path:np})}}return{path:[],label:"Tidak ditemukan hubungan"}},
  _dr(path){const r=path.map(s=>s.rel).join("-");const M={"parent":"Orang Tua","child":"Anak","spouse":"Pasangan","parent-parent":"Kakek/Nenek","child-child":"Cucu","parent-child":"Saudara Kandung","parent-spouse":"Mertua","spouse-parent":"Mertua","child-spouse":"Menantu","parent-parent-child":"Paman/Bibi","parent-child-child":"Keponakan","parent-parent-child-child":"Sepupu","child-child-child":"Cicit"};if(M[r])return M[r];let u=0,d=0;path.forEach(s=>{if(s.rel==="parent")u++;else if(s.rel==="child")d++});if(u>0&&d===0)return`${u} generasi ke atas`;if(d>0&&u===0)return`${d} generasi ke bawah`;return`${path.length} langkah`},
  bdays(pp,days=90){const now=new Date();return pp.filter(p=>p.birthDate&&!p.deathDate).map(p=>{const bd=new Date(p.birthDate);const nx=new Date(now.getFullYear(),bd.getMonth(),bd.getDate());if(nx<now)nx.setFullYear(nx.getFullYear()+1);const diff=Math.floor((nx-now)/864e5);return{person:p,next:nx,days:diff,age:nx.getFullYear()-bd.getFullYear()}}).filter(b=>b.days<=days).sort((a,b)=>a.days-b.days)},
  filter(pp,f){let r=[...pp];if(f.gender&&f.gender!=="all")r=r.filter(p=>p.gender===f.gender);if(f.generation!==undefined&&f.generation!=="all")r=r.filter(p=>FE.gen(pp,p.id)===parseInt(f.generation));if(f.status==="living")r=r.filter(p=>!p.deathDate);if(f.status==="deceased")r=r.filter(p=>p.deathDate);if(f.location)r=r.filter(p=>(p.location?.address||"").toLowerCase().includes(f.location.toLowerCase()));if(f.hasNik==="yes")r=r.filter(p=>p.nik);if(f.hasNik==="no")r=r.filter(p=>!p.nik);return r},
  // ── FARAIDH ──
  faraidh:{
    getHeirs(pp,did){const d=pp.find(p=>p.id===did);if(!d)return[];const h=[];const spouse=FE.sp(pp,d);if(spouse&&!spouse.deathDate)h.push({...spouse,relation:d.gender==="male"?"istri":"suami"});const parent=FE.pa(pp,d);if(parent&&!parent.deathDate)h.push({...parent,relation:parent.gender==="male"?"ayah":"ibu"});if(parent&&parent.gender==="male"){const m=FE.sp(pp,parent);if(m&&m.id!==d.id&&!m.deathDate&&!h.find(x=>x.id===m.id))h.push({...m,relation:"ibu"});}if(parent&&parent.gender==="female"){const f2=FE.sp(pp,parent);if(f2&&f2.id!==d.id&&!f2.deathDate&&!h.find(x=>x.id===f2.id))h.push({...f2,relation:"ayah"});}FE.ch(pp,did).filter(c=>!c.deathDate).forEach(c=>h.push({...c,relation:c.gender==="male"?"anak_laki":"anak_perempuan"}));const hasC=h.some(x=>x.relation.startsWith("anak"));const hasF=h.some(x=>x.relation==="ayah");if(!hasC&&!hasF)FE.sib(pp,d).filter(s=>!s.deathDate).forEach(s=>h.push({...s,relation:s.gender==="male"?"saudara_laki":"saudara_perempuan"}));return h},
    calc(pp,did,total,hutang=0,wasiat=0){const d=pp.find(p=>p.id===did);if(!d)return{error:"Pewaris tidak ditemukan",shares:[]};const heirs=this.getHeirs(pp,did);if(!heirs.length)return{error:"Tidak ada ahli waris",shares:[]};const mxW=(total-hutang)/3;const aW=Math.min(wasiat,mxW);const hw=total-hutang-aW;if(hw<=0)return{error:"Harta tidak cukup",shares:[]};
      const suami=heirs.find(h=>h.relation==="suami"),istri=heirs.filter(h=>h.relation==="istri"),ayah=heirs.find(h=>h.relation==="ayah"),ibu=heirs.find(h=>h.relation==="ibu");
      const aL=heirs.filter(h=>h.relation==="anak_laki"),aP=heirs.filter(h=>h.relation==="anak_perempuan"),sL=heirs.filter(h=>h.relation==="saudara_laki"),sP=heirs.filter(h=>h.relation==="saudara_perempuan");
      const hasA=aL.length+aP.length>0,hasS=sL.length+sP.length>0;const sh=[];let sisa=1;
      if(suami){const f=hasA?1/4:1/2;sh.push({person:suami,relation:"Suami",fraction:f,basis:hasA?"¼":"½",type:"furudh"});sisa-=f}
      if(istri.length){const f=hasA?1/8:1/4;istri.forEach(i=>sh.push({person:i,relation:"Istri",fraction:f/istri.length,basis:hasA?"⅛":"¼",type:"furudh"}));sisa-=f}
      if(ayah){if(hasA){sh.push({person:ayah,relation:"Ayah",fraction:1/6,basis:"⅙",type:"furudh"});sisa-=1/6}else sh.push({person:ayah,relation:"Ayah",fraction:null,basis:"Ashabah",type:"ashabah"})}
      if(ibu){const f=hasA||(hasS&&sL.length+sP.length>=2)?1/6:1/3;sh.push({person:ibu,relation:"Ibu",fraction:f,basis:f===1/6?"⅙":"⅓",type:"furudh"});sisa-=f}
      if(aL.length>0&&aP.length>0){const tp=aL.length*2+aP.length;const pp2=sisa/tp;aL.forEach(a=>sh.push({person:a,relation:"Anak ♂",fraction:pp2*2,basis:`2:1`,type:"ashabah"}));aP.forEach(a=>sh.push({person:a,relation:"Anak ♀",fraction:pp2,basis:`2:1`,type:"ashabah"}));sisa=0}
      else if(aL.length>0){aL.forEach(a=>sh.push({person:a,relation:"Anak ♂",fraction:sisa/aL.length,basis:"Ashabah",type:"ashabah"}));sisa=0}
      else if(aP.length>0){if(aP.length===1){const f=Math.min(.5,sisa);sh.push({person:aP[0],relation:"Anak ♀",fraction:f,basis:"½",type:"furudh"});sisa-=f}else{const f=Math.min(2/3,sisa);aP.forEach(a=>sh.push({person:a,relation:"Anak ♀",fraction:f/aP.length,basis:"⅔",type:"furudh"}));sisa-=f}}
      if(!hasA&&!ayah&&hasS){if(sL.length&&sP.length){const tp=sL.length*2+sP.length;const pp2=sisa/tp;sL.forEach(s=>sh.push({person:s,relation:"Saudara ♂",fraction:pp2*2,basis:"2:1",type:"ashabah"}));sP.forEach(s=>sh.push({person:s,relation:"Saudara ♀",fraction:pp2,basis:"2:1",type:"ashabah"}));sisa=0}else if(sL.length){sL.forEach(s=>sh.push({person:s,relation:"Saudara ♂",fraction:sisa/sL.length,basis:"Ashabah",type:"ashabah"}));sisa=0}else if(sP.length===1){const f=Math.min(.5,sisa);sh.push({person:sP[0],relation:"Saudara ♀",fraction:f,basis:"½",type:"furudh"});sisa-=f}else{const f=Math.min(2/3,sisa);sP.forEach(s=>sh.push({person:s,relation:"Saudara ♀",fraction:f/sP.length,basis:"⅔",type:"furudh"}));sisa-=f}}
      const ayahSh=sh.find(s=>s.person.id===ayah?.id&&s.type==="ashabah");if(ayahSh&&sisa>0){ayahSh.fraction=sisa;sisa=0}
      if(sisa>0.001){const fh=sh.filter(s=>s.type==="furudh"&&s.relation!=="Suami"&&s.relation!=="Istri");if(fh.length){const tf=fh.reduce((s,h)=>s+h.fraction,0);fh.forEach(h=>{h.fraction+=sisa*(h.fraction/tf);h.basis+=" +radd"});sisa=0}}
      return{pewaris:d,totalHarta:total,hutang,wasiat:aW,hartaWarisan:hw,shares:sh.map(s=>({...s,pct:((s.fraction||0)*100).toFixed(2),amt:Math.round((s.fraction||0)*hw)})),sisa,sisaAmt:Math.round(sisa*hw)};
    }
  },
};
// ─── LAYOUT ──────────────────────────────────────────────────
function autoLayout(pp){const roots=pp.filter(p=>!p.parentId&&!pp.some(x=>x.spouseId===p.id&&x.parentId));const pos={};function lay(pid,d){const p=pp.find(x=>x.id===pid);if(!p||pos[pid])return{x:0,w:0};const sp=FE.sp(pp,p);const ch=FE.ch(pp,pid);const cw=sp?CW*2+CG:CW;if(!ch.length){pos[pid]={x:0,y:d*(CH+GY)};if(sp&&!pos[sp.id])pos[sp.id]={x:CW+CG,y:d*(CH+GY)};return{x:0,w:cw}}const cls=[];let cur=0;ch.forEach(c=>{const cl=lay(c.id,d+1);cls.push({...cl,offset:cur});cur+=cl.w+GX});const tcw=cur-GX;const cx=(cls[0].offset+cls[cls.length-1].offset+cls[cls.length-1].w)/2-cw/2;const px=Math.max(0,cx);pos[pid]={x:px,y:d*(CH+GY)};if(sp&&!pos[sp.id])pos[sp.id]={x:px+CW+CG,y:d*(CH+GY)};const cbx=px+cw/2-tcw/2;ch.forEach((c,i)=>shift(c.id,cbx+cls[i].offset));return{x:Math.min(px,cbx),w:Math.max(px+cw,cbx+tcw)-Math.min(px,cbx)}}function shift(pid,dx){if(!pos[pid])return;pos[pid].x+=dx;const sp=FE.sp(pp,pp.find(x=>x.id===pid));if(sp&&pos[sp.id])pos[sp.id].x+=dx;FE.ch(pp,pid).forEach(c=>shift(c.id,dx))}let gc=0;roots.forEach(root=>{lay(root.id,0);const sa=pid=>{if(pos[pid])pos[pid].x+=gc;const sp=FE.sp(pp,pp.find(x=>x.id===pid));if(sp&&pos[sp.id])pos[sp.id].x+=gc;FE.ch(pp,pid).forEach(c=>sa(c.id))};sa(root.id);let mxX=0;Object.values(pos).forEach(p=>mxX=Math.max(mxX,p.x));gc=mxX+CW+GX*3});let mnX=Infinity,mnY=Infinity;Object.values(pos).forEach(p=>{mnX=Math.min(mnX,p.x);mnY=Math.min(mnY,p.y)});Object.values(pos).forEach(p=>{p.x-=mnX-100;p.y-=mnY-80});return pos}
function getConns(pp,pos){const L=[];pp.forEach(p=>{const ps=pos[p.id];if(!ps)return;const sp=FE.sp(pp,p);if(sp&&pos[sp.id]&&p.id<sp.id)L.push({t:"sp",x1:ps.x+CW,y1:ps.y+CH/2,x2:pos[sp.id].x,y2:ps.y+CH/2});const ch=FE.ch(pp,p.id);if(ch.length){const cw=sp&&pos[sp.id]?(pos[sp.id].x+CW-ps.x):CW;const pcx=ps.x+cw/2,pb=ps.y+CH;const ct=ch.map(c=>{const cp=pos[c.id];if(!cp)return null;const cs=FE.sp(pp,c);const ccw=cs&&pos[cs.id]?(pos[cs.id].x+CW-cp.x):CW;return{cx:cp.x+ccw/2,y:cp.y}}).filter(Boolean);if(ct.length){const my=pb+GY/2;L.push({t:"pd",x1:pcx,y1:pb,x2:pcx,y2:my});if(ct.length>1)L.push({t:"br",x1:Math.min(...ct.map(c=>c.cx)),y1:my,x2:Math.max(...ct.map(c=>c.cx)),y2:my});ct.forEach(c=>L.push({t:"cd",x1:c.cx,y1:my,x2:c.cx,y2:c.y}))}}});return L}
// ─── SEED ────────────────────────────────────────────────────
const SEED=(()=>{const I={a:"p1",b:"p2",c:"p3",d:"p4",e:"p5",f:"p6",g:"p7",h:"p8",i:"p9",j:"p10",k:"p11",l:"p12",m:"p13",n:"p14",o:"p15",p:"p16",q:"p17",r:"p18",s:"p19",t:"p20",u:"p21",v:"p22",w:"p23",x:"p24",y:"p25",z:"p26",aa:"p27"};const P=(id,nm,gn,pid,sid,nt="",loc=null,nik="")=>({id,name:nm,gender:gn,birthDate:"",deathDate:"",birthPlace:loc?loc.address:"",photo:"",notes:nt,parentId:pid,spouseId:sid,location:loc,nik,createdAt:"2024-01-01"});const S={lat:-0.4948,lng:117.1436,address:"Samarinda, Kaltim"},C={lat:-6.354,lng:106.743,address:"Ciputat, Tangsel"};return[P(I.a,"HM Syachroel AP","male",null,I.b,"Kepala Keluarga",S),P(I.b,"Hj. Djahora","female",null,I.a,"Ibu Keluarga",S),P(I.c,"Isnawati","female",I.a,I.d,"Anak ke-1",S),P(I.d,"Abdul Kadir Saro","male",null,I.c,"Suami Isnawati",S),P(I.e,"M Fakhruddin","male",I.a,I.f,"Anak ke-2",S),P(I.f,"Ertika Sari","female",null,I.e,"Istri Fakhruddin",S),P(I.g,"Budiana","female",I.a,I.h,"Anak ke-3",S),P(I.h,"Fadlan","male",null,I.g,"Suami Budiana",S),P(I.i,"M Sopian Hadianto","male",I.a,I.j,"Anak ke-4 • GRC Expert & AI Builder",C),P(I.j,"Susilowati","female",null,I.i,"Istri Sopian",C),P(I.k,"M. Firmansyah","male",I.a,I.l,"Anak ke-5",S),P(I.l,"Rissa","female",null,I.k,"Istri Firmansyah",S),P(I.m,"M Reza Fahlevi","male",I.a,I.n,"Anak ke-6",S),P(I.n,"Amy","female",null,I.m,"Istri Reza",S),P(I.o,"Aulia Rahman","male",I.c,null,"Cucu",S),P(I.p,"Abdul Haris","male",I.c,null,"Cucu",S),P(I.q,"Annisa Salsabila","female",I.e,null,"Cucu",S),P(I.r,"M Rayhan","male",I.e,null,"Cucu",S),P(I.s,"Syifa","female",I.e,null,"Cucu",S),P(I.t,"Khalisa NF Shasie","female",I.i,null,"Cucu",C),P(I.u,"Athallah Lintang Ahmad","male",I.i,null,"Cucu",C),P(I.v,"Syakira Alma Kinanti","female",I.i,null,"Cucu",C),P(I.w,"Kaylila Syafira","female",I.k,null,"Cucu",S),P(I.x,"Al Gazel","male",I.k,null,"Cucu",S),P(I.y,"Al Syameera","female",I.k,null,"Cucu",S),P(I.z,"Caca","female",I.m,null,"Cucu",S),P(I.aa,"Fia","female",I.m,null,"Cucu",S)]})();
// ─── STYLES ──────────────────────────────────────────────────
const css=`@import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');@import url('https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css');:root{--bg0:#07090e;--bg1:#0c1017;--bg2:#131821;--bg3:#1a2030;--bdr:#1e2738;--bdr2:#2c3a50;--t1:#e4e8f0;--t2:#7d8ba0;--t3:#4d5a70;--pri:#14b8a6;--pri2:#0d9488;--acc:#6366f1;--warn:#f59e0b;--rose:#ec4899;--purple:#8b5cf6;--orange:#f97316;--male-bg:#0f1a2e;--male-bdr:#1a3050;--male-t:#38bdf8;--fem-bg:#1e0f28;--fem-bdr:#3a1850;--fem-t:#d946ef;--r:8px;--rs:6px;--fd:'Instrument Serif',serif;--fb:'DM Sans',sans-serif;--fm:'JetBrains Mono',monospace}*{margin:0;padding:0;box-sizing:border-box}body,#root{font-family:var(--fb);background:var(--bg0);color:var(--t1);min-height:100vh;overflow:hidden}.app{height:100vh;display:flex;flex-direction:column}
.auth-w{height:100vh;display:flex;overflow:hidden}.auth-hero{flex:1;display:flex;flex-direction:column;justify-content:center;padding:48px;background:linear-gradient(160deg,#080c14,#0a1020 50%,#0c1428);position:relative;overflow:hidden}.auth-hero::before{content:'';position:absolute;top:-100px;right:-100px;width:350px;height:350px;border-radius:50%;background:radial-gradient(circle,rgba(20,184,166,.07),transparent 70%)}.auth-brand{margin-bottom:32px}.auth-brand h1{font-family:var(--fd);font-size:48px;color:var(--t1);letter-spacing:-1px}.auth-brand h1 em{font-style:italic;color:var(--pri)}.auth-brand p{font-size:14px;color:var(--t3);margin-top:6px}.auth-feats{display:flex;flex-direction:column;gap:10px}.auth-feat{display:flex;align-items:flex-start;gap:10px;padding:10px 14px;border-radius:var(--r);border:1px solid var(--bdr);background:rgba(20,184,166,.02);transition:all .2s}.auth-feat:hover{border-color:var(--pri);background:rgba(20,184,166,.05)}.auth-feat-ic{width:32px;height:32px;border-radius:7px;background:var(--bg2);display:flex;align-items:center;justify-content:center;font-size:15px;flex-shrink:0;border:1px solid var(--bdr)}.auth-feat h4{font-size:12px;font-weight:600}.auth-feat p{font-size:10px;color:var(--t3);line-height:1.3}.auth-fs{width:380px;display:flex;align-items:center;justify-content:center;padding:36px;background:var(--bg1);border-left:1px solid var(--bdr)}.auth-f{width:100%}.auth-f h2{font-family:var(--fd);font-size:24px;margin-bottom:3px}.auth-f .sub{font-size:11px;color:var(--t3);margin-bottom:20px}.auth-trust{display:flex;gap:14px;margin-top:16px;padding-top:14px;border-top:1px solid var(--bdr)}.auth-trust span{font-size:9px;color:var(--t3);display:flex;align-items:center;gap:3px}
.dash{height:100vh;display:flex;flex-direction:column}.dash-h{background:var(--bg1);border-bottom:1px solid var(--bdr);padding:12px 24px;display:flex;align-items:center;justify-content:space-between}.dash-h h1{font-family:var(--fd);font-size:20px}.dash-h h1 em{color:var(--pri);font-style:italic}.dash-u{display:flex;align-items:center;gap:8px;font-size:12px}.dash-av{width:30px;height:30px;border-radius:7px;background:var(--bg3);display:flex;align-items:center;justify-content:center;font-weight:700;font-size:10px;color:var(--pri);border:1px solid var(--bdr)}.dash-b{flex:1;overflow:auto;padding:24px}.dash-g{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px;max-width:900px;margin:0 auto}.fcard{background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);padding:18px;cursor:pointer;transition:all .25s;position:relative;overflow:hidden}.fcard:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.3);border-color:var(--bdr2)}.fcard-bar{height:2px;background:linear-gradient(90deg,var(--pri),var(--acc));position:absolute;top:0;left:0;right:0}.fcard h3{font-family:var(--fd);font-size:16px;margin-top:3px}.fcard p{font-size:11px;color:var(--t3);margin:3px 0 10px}.fcard-st{display:flex;gap:10px;font-size:10px;color:var(--t2)}.fcard-rl{position:absolute;top:8px;right:10px;font-size:8px;padding:2px 6px;border-radius:5px;font-weight:600;text-transform:uppercase;font-family:var(--fm)}.fnew{border:2px dashed var(--bdr);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;color:var(--t3);min-height:130px;transition:all .25s}.fnew:hover{border-color:var(--pri);color:var(--pri)}
.ws-h{background:var(--bg1);border-bottom:1px solid var(--bdr);padding:8px 16px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;z-index:100;flex-shrink:0}.ws-br{display:flex;align-items:center;gap:6px}.ws-br h1{font-family:var(--fd);font-size:15px}.ws-br h1 em{color:var(--pri);font-style:italic}.ws-tag{font-size:7px;font-family:var(--fm);background:var(--pri);color:#000;padding:1px 4px;border-radius:3px;font-weight:600}.ws-act{display:flex;gap:5px;align-items:center;margin-left:auto;flex-wrap:wrap}
.btn{display:inline-flex;align-items:center;gap:4px;padding:5px 10px;border-radius:var(--rs);border:1px solid var(--bdr);background:var(--bg2);color:var(--t1);font-size:11px;font-weight:500;cursor:pointer;transition:all .2s;font-family:var(--fb);white-space:nowrap}.btn:hover{background:var(--bg3);border-color:var(--bdr2);transform:translateY(-1px)}.btn-p{background:var(--pri);border-color:var(--pri);color:#000;font-weight:600}.btn-p:hover{background:var(--pri2)}.btn-d{background:#3f1219;border-color:#5f1d2d;color:#fca5a5}.btn-sm{padding:3px 7px;font-size:10px}.btn-icon{padding:4px;width:26px;height:26px;justify-content:center}.btn-ghost{background:transparent;border-color:transparent}.btn-ghost:hover{background:var(--bg2)}.btn-block{width:100%;justify-content:center;padding:9px}
.nav{display:flex;gap:1px;background:var(--bg0);border-radius:var(--rs);padding:2px;border:1px solid var(--bdr)}.navt{padding:5px 9px;border-radius:4px;border:none;background:transparent;color:var(--t3);font-size:10px;font-weight:500;cursor:pointer;transition:all .2s;font-family:var(--fb)}.navt:hover{color:var(--t2)}.navt.on{background:var(--bg2);color:var(--pri);box-shadow:0 1px 5px rgba(0,0,0,.2)}
.sbox{display:flex;align-items:center;gap:5px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--rs);padding:4px 8px;min-width:110px}.sbox input{background:transparent;border:none;outline:none;color:var(--t1);font-size:10px;width:100%;font-family:var(--fb)}.sbox input::placeholder{color:var(--t3)}
.fg{margin-bottom:12px}.fl{display:block;font-size:10px;font-weight:600;color:var(--t2);margin-bottom:4px}.fi,.fsel,.fta{width:100%;padding:7px 10px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--rs);color:var(--t1);font-size:12px;font-family:var(--fb);outline:none;transition:border .2s}.fi:focus,.fsel:focus,.fta:focus{border-color:var(--pri);box-shadow:0 0 0 2px rgba(20,184,166,.08)}.fta{resize:vertical;min-height:44px}.fr{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.gtog{display:flex;gap:5px}.gbtn{flex:1;padding:7px;border-radius:var(--rs);border:2px solid var(--bdr);background:var(--bg2);color:var(--t3);font-size:11px;font-weight:600;cursor:pointer;transition:all .2s;display:flex;align-items:center;justify-content:center;gap:4px;font-family:var(--fb)}.gbtn.am{border-color:var(--male-t);background:var(--male-bg);color:var(--male-t)}.gbtn.af{border-color:var(--fem-t);background:var(--fem-bg);color:var(--fem-t)}
.modal-ov{position:fixed;inset:0;background:rgba(0,0,0,.75);backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center;z-index:200;padding:12px}.modal{background:var(--bg1);border:1px solid var(--bdr);border-radius:10px;width:100%;max-width:460px;max-height:85vh;overflow-y:auto;box-shadow:0 14px 40px rgba(0,0,0,.5);animation:mU .2s ease}@keyframes mU{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.m-h{display:flex;align-items:center;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--bdr)}.m-h h2{font-family:var(--fd);font-size:17px}.m-b{padding:14px 18px}.m-f{padding:10px 18px;display:flex;gap:5px;justify-content:flex-end;border-top:1px solid var(--bdr)}
.cvs{flex:1;position:relative;overflow:hidden;background:var(--bg0);cursor:grab}.cvs.grabbing{cursor:grabbing}.cvs-in{position:absolute;top:0;left:0;transform-origin:0 0}
.cc{position:absolute;width:${CW}px;min-height:${CH}px;background:var(--bg2);border:1px solid var(--bdr);border-radius:12px;cursor:grab;user-select:none;transition:transform .15s,box-shadow .2s,border-color .2s;overflow:visible;z-index:10;display:flex;flex-direction:column;align-items:center;padding-top:10px}.cc:hover{z-index:20;border-color:var(--bdr2);box-shadow:0 4px 16px rgba(0,0,0,.35)}.cc.dragging{z-index:50;box-shadow:0 8px 28px rgba(0,0,0,.5);opacity:.92;cursor:grabbing;transform:scale(1.02)}.cc.selected{border-color:var(--pri);box-shadow:0 0 0 2px rgba(20,184,166,.18),0 4px 16px rgba(0,0,0,.35)}.cc.male{border-top:${ACCENT_H}px solid var(--male-t)}.cc.female{border-top:${ACCENT_H}px solid var(--fem-t)}.cc.deceased{opacity:.62}.cc.deceased::after{content:'almh.';position:absolute;bottom:6px;right:8px;font-size:8px;font-family:var(--fm);color:var(--t3);font-weight:500;letter-spacing:.4px}.cc.b0{background:var(--bg2)}.cc.b1{background:linear-gradient(rgba(20,184,166,.05),rgba(20,184,166,.05)),var(--bg2)}.cc.b2{background:linear-gradient(rgba(99,102,241,.05),rgba(99,102,241,.05)),var(--bg2)}.cc.b3{background:linear-gradient(rgba(245,158,11,.05),rgba(245,158,11,.05)),var(--bg2)}.cc.b4{background:linear-gradient(rgba(236,72,153,.05),rgba(236,72,153,.05)),var(--bg2)}.cc.b5{background:linear-gradient(rgba(139,92,246,.05),rgba(139,92,246,.05)),var(--bg2)}.cc.b6{background:linear-gradient(rgba(249,115,22,.05),rgba(249,115,22,.05)),var(--bg2)}.cc.b7{background:linear-gradient(rgba(14,165,233,.05),rgba(14,165,233,.05)),var(--bg2)}.cc-av{width:46px;height:46px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:600;font-family:var(--fd);flex-shrink:0;background:var(--bg1);margin-bottom:6px}.cc-av.male{color:var(--male-t);border:1.5px solid var(--male-bdr)}.cc-av.female{color:var(--fem-t);border:1.5px solid var(--fem-bdr)}.cc-nm{font-size:13px;font-weight:500;line-height:1.25;text-align:center;padding:0 10px;max-width:100%;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.cc-mt{font-size:11px;color:var(--t3);margin-top:4px;text-align:center;font-family:var(--fm);letter-spacing:.2px}.cc-badge-gen{position:absolute;top:6px;left:6px;font-size:9px;font-family:var(--fm);font-weight:600;padding:2px 6px;border-radius:8px;background:var(--bg1);color:var(--t3);letter-spacing:.3px}.cc-badge-nik{position:absolute;top:6px;right:6px;font-size:8px;font-family:var(--fm);font-weight:600;padding:2px 5px;border-radius:8px;background:rgba(20,184,166,.12);color:var(--pri);letter-spacing:.4px}
.conn-svg{position:absolute;top:0;left:0;pointer-events:none;z-index:5}.zm{position:absolute;bottom:12px;right:12px;display:flex;flex-direction:column;gap:3px;z-index:60}.zm button{width:28px;height:28px;border-radius:var(--rs);border:1px solid var(--bdr);background:var(--bg2);color:var(--t1);font-size:14px;cursor:pointer;display:flex;align-items:center;justify-content:center;font-family:var(--fb)}.zm button:hover{background:var(--bg3)}.mm{position:absolute;bottom:12px;left:12px;width:140px;height:70px;background:var(--bg1);border:1px solid var(--bdr);border-radius:var(--rs);overflow:hidden;z-index:60;opacity:.7}.mm:hover{opacity:1}
.sb{position:absolute;top:0;right:0;bottom:0;width:300px;background:var(--bg1);border-left:1px solid var(--bdr);z-index:80;overflow-y:auto;animation:sI .2s ease}@keyframes sI{from{transform:translateX(100%)}to{transform:translateX(0)}}.sb-h{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid var(--bdr)}.sb-h h3{font-family:var(--fd);font-size:14px}.sb-b{padding:12px 14px}.sb-av{width:50px;height:50px;border-radius:10px;display:flex;align-items:center;justify-content:center;margin:0 auto 8px;font-size:20px;font-weight:700;font-family:var(--fd)}.sb-av.male{background:var(--male-bg);color:var(--male-t);border:2px solid var(--male-bdr)}.sb-av.female{background:var(--fem-bg);color:var(--fem-t);border:2px solid var(--fem-bdr)}.sb-nm{text-align:center;font-family:var(--fd);font-size:16px;margin-bottom:2px}.sb-sub{text-align:center;font-size:9px;color:var(--t3);margin-bottom:5px}.sb-ctx{text-align:center;font-size:8px;color:var(--t3);margin-bottom:12px;padding:4px 6px;background:var(--bg2);border-radius:var(--rs)}.sb-sec{margin-bottom:12px}.sb-sec-t{font-size:8px;font-weight:700;color:var(--t3);letter-spacing:.7px;text-transform:uppercase;margin-bottom:5px;padding-bottom:3px;border-bottom:1px solid var(--bdr);font-family:var(--fm)}.sb-row{display:flex;justify-content:space-between;padding:2px 0;font-size:10px}.sb-row-l{color:var(--t3)}.sb-row-v{font-weight:500;text-align:right;max-width:160px}.sb-rel{display:flex;align-items:center;gap:6px;padding:5px 7px;background:var(--bg2);border-radius:var(--rs);cursor:pointer;transition:all .15s;font-size:10px;margin-bottom:2px}.sb-rel:hover{background:var(--bg3)}.sb-rel-t{font-size:7px;color:var(--t3);font-weight:600;letter-spacing:.3px;text-transform:uppercase;min-width:48px;font-family:var(--fm)}.sb-ft{padding:8px 14px;border-top:1px solid var(--bdr);display:flex;gap:4px;justify-content:flex-end}
.map-w{width:100%;height:100%;position:relative}.map-c{width:100%;height:100%}.map-leg{position:absolute;top:8px;right:8px;background:var(--bg1);border:1px solid var(--bdr);border-radius:var(--r);padding:8px 10px;z-index:1000;min-width:130px}.map-leg-t{font-size:8px;font-weight:700;color:var(--t3);letter-spacing:.7px;text-transform:uppercase;margin-bottom:5px;font-family:var(--fm)}.map-leg-i{display:flex;align-items:center;gap:6px;font-size:9px;margin-bottom:2px;color:var(--t2);cursor:pointer}.map-leg-d{width:7px;height:7px;border-radius:50%;flex-shrink:0}.map-bar{position:absolute;bottom:8px;left:8px;display:flex;gap:4px;z-index:1000}.map-st{background:var(--bg1);border:1px solid var(--bdr);border-radius:var(--rs);padding:3px 6px;font-size:8px;color:var(--t2);font-family:var(--fm)}.map-st b{color:var(--t1)}.leaflet-popup-content-wrapper{border-radius:8px!important}
.lv{display:flex;flex-direction:column;gap:4px;max-width:760px;margin:0 auto;padding:14px}.li{display:flex;align-items:center;gap:9px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);padding:8px 10px;cursor:pointer;transition:all .2s}.li:hover{background:var(--bg3);transform:translateX(2px)}.li-av{width:30px;height:30px;border-radius:7px;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:11px;flex-shrink:0;font-family:var(--fd)}.li-av.male{background:var(--male-bg);color:var(--male-t)}.li-av.female{background:var(--fem-bg);color:var(--fem-t)}.li-info{flex:1;min-width:0}.li-info h4{font-size:11px;font-weight:600}.li-info p{font-size:9px;color:var(--t3)}.li-badge{font-size:7px;padding:2px 5px;border-radius:3px;font-weight:600;font-family:var(--fm)}
.sg{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px;max-width:760px;margin:0 auto;padding:14px}.sc{background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);padding:12px;text-align:center;transition:all .2s}.sc:hover{transform:translateY(-1px);box-shadow:0 3px 12px rgba(0,0,0,.2)}.sc-v{font-family:var(--fd);font-size:26px}.sc-l{font-size:8px;color:var(--t3);font-weight:500;letter-spacing:.4px;text-transform:uppercase;margin-top:1px;font-family:var(--fm)}
.tl{max-width:560px;margin:0 auto;padding:14px 14px 14px 40px;position:relative}.tl::before{content:'';position:absolute;left:20px;top:14px;bottom:14px;width:1.5px;background:var(--bdr)}.tl-i{position:relative;margin-bottom:10px;padding:8px 10px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);cursor:pointer;transition:all .2s}.tl-i:hover{background:var(--bg3);transform:translateX(2px)}.tl-dot{width:7px;height:7px;border-radius:50%;position:absolute;left:-26px;top:12px;border:2px solid var(--bg0)}.tl-yr{font-size:8px;color:var(--pri);font-weight:600;font-family:var(--fm)}.tl-tt{font-size:11px;font-weight:600}
.ins{padding:14px;max-width:820px;margin:0 auto;overflow:auto;height:100%}.ins-g{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ins-c{background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);padding:12px;transition:all .2s}.ins-c:hover{border-color:var(--bdr2)}.ins-cf{grid-column:1/-1}.ins-c h3{font-family:var(--fd);font-size:13px;margin-bottom:8px;display:flex;align-items:center;gap:6px}.ins-c h3 span{font-size:14px}
.wr{padding:14px;max-width:820px;margin:0 auto;overflow:auto;height:100%}.wr-hd{text-align:center;margin-bottom:16px;padding:16px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r)}.wr-hd h2{font-family:var(--fd);font-size:20px}.wr-hd h2 em{color:var(--pri);font-style:italic}.wr-hd p{font-size:10px;color:var(--t3)}.wr-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}.wr-ff{grid-column:1/-1}.wr-ig{background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);padding:12px}.wr-ig label{font-size:9px;font-weight:600;color:var(--t3);text-transform:uppercase;letter-spacing:.4px;margin-bottom:5px;display:block;font-family:var(--fm)}.wr-ig input,.wr-ig select{width:100%;padding:7px 9px;background:var(--bg3);border:1px solid var(--bdr);border-radius:var(--rs);color:var(--t1);font-size:12px;font-family:var(--fb);outline:none}.wr-ig input:focus,.wr-ig select:focus{border-color:var(--pri)}.wr-res{background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r);overflow:hidden}.wr-rh{padding:12px 14px;background:linear-gradient(135deg,rgba(20,184,166,.06),rgba(99,102,241,.04));border-bottom:1px solid var(--bdr)}.wr-rh h3{font-family:var(--fd);font-size:14px}.wr-rh p{font-size:10px;color:var(--t3)}.wr-ded{display:flex;gap:6px;padding:10px 14px;border-bottom:1px solid var(--bdr);flex-wrap:wrap}.wr-dd{padding:4px 8px;background:var(--bg3);border-radius:var(--rs);font-size:9px;color:var(--t2);font-family:var(--fm)}.wr-dd b{color:var(--t1)}.wr-sr{display:flex;align-items:center;gap:8px;padding:8px 14px;border-bottom:1px solid var(--bdr);transition:background .15s}.wr-sr:hover{background:var(--bg3)}.wr-sr:last-child{border-bottom:none}.wr-sr-av{width:28px;height:28px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:700;font-family:var(--fd);flex-shrink:0}.wr-sr-av.male{background:var(--male-bg);color:var(--male-t)}.wr-sr-av.female{background:var(--fem-bg);color:var(--fem-t)}.wr-sr-info{flex:1}.wr-sr-nm{font-size:11px;font-weight:600}.wr-sr-rl{font-size:8px;color:var(--t3);font-family:var(--fm)}.wr-sr-bs{font-size:8px;color:var(--t3);background:var(--bg3);padding:1px 5px;border-radius:3px;font-family:var(--fm)}.wr-sr-pct{font-size:13px;font-weight:700;font-family:var(--fd);min-width:44px;text-align:right}.wr-sr-amt{font-size:10px;color:var(--pri);font-family:var(--fm);min-width:80px;text-align:right}.wr-dis{padding:10px 14px;font-size:8px;color:var(--t3);line-height:1.5;background:rgba(245,158,11,.02);border-top:1px solid var(--bdr)}
.nik-box{background:var(--bg3);border:1px solid var(--bdr);border-radius:var(--rs);padding:8px 10px;margin-top:4px}.nik-box input{width:100%;padding:6px 8px;background:var(--bg2);border:1px solid var(--bdr);border-radius:4px;color:var(--t1);font-size:12px;font-family:var(--fm);outline:none;letter-spacing:1px}.nik-box input:focus{border-color:var(--pri)}.nik-result{margin-top:6px;padding:6px 8px;background:var(--bg2);border-radius:4px;font-size:9px;line-height:1.6}.nik-ok{color:var(--pri)}.nik-err{color:var(--rose)}
.geo-w{background:var(--bg3);border:1px solid var(--bdr);border-radius:var(--rs);padding:7px 9px;margin-top:4px}.geo-r{display:flex;gap:4px;align-items:center;margin-bottom:4px}.geo-r:last-child{margin-bottom:0}.geo-l{font-size:7px;color:var(--t3);min-width:22px;font-weight:600;font-family:var(--fm)}.geo-w input{flex:1;padding:4px 6px;background:var(--bg2);border:1px solid var(--bdr);border-radius:3px;color:var(--t1);font-size:9px;font-family:var(--fb);outline:none}.geo-w input:focus{border-color:var(--pri)}.geo-res{background:var(--bg2);border:1px solid var(--bdr);border-radius:3px;margin-top:3px;max-height:80px;overflow-y:auto}.geo-ri{padding:3px 6px;font-size:8px;cursor:pointer;color:var(--t2);border-bottom:1px solid var(--bdr)}.geo-ri:hover{background:var(--bg3);color:var(--t1)}.geo-ri:last-child{border-bottom:none}
.collab-i{display:flex;align-items:center;gap:7px;padding:5px 7px;background:var(--bg2);border-radius:var(--rs);margin-bottom:4px;font-size:10px}.collab-av{width:24px;height:24px;border-radius:5px;background:var(--bg3);display:flex;align-items:center;justify-content:center;font-size:8px;font-weight:700;color:var(--pri)}.collab-info{flex:1}.collab-info span{display:block;font-size:8px;color:var(--t3)}.collab-rl{font-size:7px;padding:1px 4px;border-radius:3px;font-weight:600;font-family:var(--fm)}
.fbar{display:flex;gap:4px;flex-wrap:wrap;margin-bottom:8px;padding:6px 10px;background:var(--bg2);border:1px solid var(--bdr);border-radius:var(--r)}.fbar select{padding:3px 6px;background:var(--bg3);border:1px solid var(--bdr);border-radius:3px;color:var(--t1);font-size:9px;font-family:var(--fb);outline:none}.fbar select:focus{border-color:var(--pri)}.fbar label{font-size:8px;color:var(--t3);display:flex;flex-direction:column;gap:2px}.ftag{display:inline-flex;align-items:center;gap:2px;padding:2px 6px;background:var(--pri);color:#000;border-radius:8px;font-size:8px;font-weight:600;cursor:pointer}
.empty{text-align:center;padding:40px 14px;color:var(--t3)}.empty h3{font-family:var(--fd);font-size:17px;color:var(--t2);margin-bottom:3px}.empty p{font-size:11px;margin-bottom:12px}
.toast{position:fixed;bottom:14px;left:50%;transform:translateX(-50%);background:var(--bg2);border:1px solid var(--pri);color:var(--pri);padding:7px 14px;border-radius:var(--r);font-size:10px;font-weight:500;box-shadow:0 5px 20px rgba(0,0,0,.4);z-index:300;animation:mU .2s ease,fO .3s ease 2.5s forwards}@keyframes fO{to{opacity:0}}
::-webkit-scrollbar{width:4px;height:4px}::-webkit-scrollbar-track{background:var(--bg0)}::-webkit-scrollbar-thumb{background:var(--bdr);border-radius:2px}
@media(max-width:768px){.auth-w{flex-direction:column}.auth-hero{padding:24px;flex:none}.auth-fs{width:100%;border-left:none;border-top:1px solid var(--bdr)}.ws-h{padding:6px 10px}.sb{width:100%}.fr,.ins-g,.wr-form{grid-template-columns:1fr}.dash-g{grid-template-columns:1fr}.navt{padding:4px 6px;font-size:9px}}`;
// ─── ICONS ───────────────────────────────────────────────────
const Ic={X:()=><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6L6 18M6 6l12 12"/></svg>,Search:()=><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg>,Plus:()=><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14"/></svg>,Edit:()=><svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>,Trash:()=><svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2"/></svg>,DL:()=><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>,Fit:()=><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 3H5a2 2 0 00-2 2v3m18 0V5a2 2 0 00-2-2h-3m0 18h3a2 2 0 002-2v-3M3 16v3a2 2 0 002 2h3"/></svg>,Share:()=><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="M8.59 13.51l6.83 3.98M15.41 6.51l-6.82 3.98"/></svg>,Back:()=><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>};
const ini=n=>{const w=(n||"").trim().split(/\s+/).filter(Boolean);if(w.length===0)return"?";if(w.length===1)return w[0].slice(0,2).toUpperCase();return(w[0][0]+w[1][0]).toUpperCase()};
// ═══════════════════════════════════════════════════════════════
// AUTH
// ═══════════════════════════════════════════════════════════════
function AuthScreen({onLogin}){const[mode,setMode]=useState("login");const[name,setName]=useState("");const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);
  const go=async()=>{setErr("");setBusy(true);if(mode==="register"){if(!name.trim()||!email.trim()||!pw.trim()){setErr("Semua field wajib diisi");setBusy(false);return}const ex=await DB.getUserByEmail(email);if(ex){setErr("Email sudah terdaftar");setBusy(false);return}onLogin(await DB.createUser({name,email,password:pw}))}else{const u=await DB.getUserByEmail(email);if(!u||u.password!==pw){setErr("Email atau password salah");setBusy(false);return}onLogin(u)}setBusy(false)};
  return(<div className="auth-w"><div className="auth-hero"><div className="auth-brand"><h1>NAS<em>AB</em></h1><p>Jaga Nasabmu — Platform Silsilah Keluarga Modern</p></div><div className="auth-feats">
    {[{ic:"⚖️",h:"Kalkulator Faraidh",p:"Hitung waris sesuai hukum Islam otomatis dari silsilah"},{ic:"🆔",h:"NIK Intelligence",p:"Auto-extract tanggal lahir, gender, lokasi dari NIK"},{ic:"🌳",h:"Drag & Drop Canvas",p:"Canvas interaktif dengan auto-connectors & generation lanes"},{ic:"🗺️",h:"Geotagging & Peta",p:"Petakan lokasi keluarga dengan Leaflet map"},{ic:"🔍",h:"Relationship Finder",p:"Cari hubungan antar anggota dengan AI pathfinding"}].map((f,i)=>(<div key={i} className="auth-feat"><div className="auth-feat-ic">{f.ic}</div><div><h4>{f.h}</h4><p>{f.p}</p></div></div>))}
  </div></div><div className="auth-fs"><div className="auth-f"><h2>{mode==="login"?"Masuk":"Daftar"}</h2><div className="sub">{mode==="login"?"Masuk ke akun NASAB":"Buat akun gratis"}</div>
    {mode==="register"&&<div style={{background:"var(--glass)",border:"1px solid var(--bd)",padding:"8px 10px",borderRadius:8,fontSize:11,color:"var(--t2)",marginBottom:4,lineHeight:1.5}}>ℹ️ Data <b>NIK</b> dan <b>Kartu Keluarga (KK)</b> bersifat <b>opsional</b> — bisa dilengkapi nanti saat menambah anggota keluarga.</div>}
    {err&&<div style={{background:"#3f1219",border:"1px solid #5f1d2d",color:"#fca5a5",padding:"6px 8px",borderRadius:5,fontSize:10,marginBottom:10}}>{err}</div>}
    {mode==="register"&&<div className="fg"><label className="fl">Nama</label><input className="fi" value={name} onChange={e=>setName(e.target.value)} placeholder="Nama lengkap"/></div>}
    <div className="fg"><label className="fl">Email</label><input className="fi" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@email.com" onKeyDown={e=>e.key==="Enter"&&go()}/></div>
    <div className="fg"><label className="fl">Password</label><input className="fi" type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="••••••" onKeyDown={e=>e.key==="Enter"&&go()}/></div>
    <button className="btn btn-p btn-block" onClick={go} disabled={busy}>{busy?"...":(mode==="login"?"Masuk →":"Buat Akun →")}</button>
    <div style={{textAlign:"center",marginTop:10,fontSize:10,color:"var(--t3)"}}>{mode==="login"?<>Belum punya akun? <span style={{color:"var(--pri)",cursor:"pointer",fontWeight:600}} onClick={()=>{setMode("register");setErr("")}}>Daftar</span></>:<>Sudah punya? <span style={{color:"var(--pri)",cursor:"pointer",fontWeight:600}} onClick={()=>{setMode("login");setErr("")}}>Masuk</span></>}</div>
    <div className="auth-trust"><span>🔒 Enkripsi</span><span>☁️ Cloud</span><span>🇮🇩 Indonesia</span></div>
  </div></div></div>)}
// ═══════════════════════════════════════════════════════════════
// DASHBOARD
// ═══════════════════════════════════════════════════════════════
function Dashboard({user,onSelect,onLogout,onCreate}){const[fams,setFams]=useState([]);const[sh,setSh]=useState(false);const[nn,setNn]=useState("");const[nd,setNd]=useState("");
  useEffect(()=>{(async()=>{const fs=[];for(const f of(user.families||[])){const fm=await DB.getFamily(f.id);if(fm)fs.push({...fm,myRole:f.role})}setFams(fs)})()},[user]);
  const cr=async()=>{if(!nn.trim())return;const f=await DB.createFamily({name:nn,description:nd,ownerId:user.id,ownerName:user.name});const u=await DB.getUser(user.id);onCreate(u,f);setSh(false);setNn("");setNd("")};
  return(<div className="dash"><header className="dash-h"><h1>NAS<em>AB</em></h1><div className="dash-u"><span style={{color:"var(--t3)",fontSize:10}}>Halo,</span><b>{user.name}</b><div className="dash-av">{ini(user.name)}</div><button className="btn btn-sm btn-ghost" onClick={onLogout}>Keluar</button></div></header>
    <div className="dash-b"><div style={{maxWidth:900,margin:"0 auto"}}><div style={{marginBottom:16}}><h2 style={{fontFamily:"var(--fd)",fontSize:20}}>Silsilah Saya</h2><p style={{fontSize:11,color:"var(--t3)",marginTop:2}}>Kelola pohon keluarga & undang kolaborator</p></div>
    <div className="dash-g">{fams.map(f=>(<div key={f.id} className="fcard" onClick={()=>onSelect(f)}><div className="fcard-bar"/><span className="fcard-rl" style={{background:f.myRole===RL.O?"var(--pri)":"var(--acc)",color:f.myRole===RL.O?"#000":"#fff"}}>{f.myRole}</span><h3>{f.name}</h3><p>{f.description||"Silsilah keluarga"}</p><div className="fcard-st"><span>👥 {f.members?.length||0}</span><span>📍 {(f.members||[]).filter(m=>m.location?.lat).length}</span></div></div>))}<div className="fcard fnew" onClick={()=>setSh(true)}><span style={{fontSize:22,color:"var(--pri)"}}>+</span><span style={{fontSize:11,fontWeight:600}}>Buat Silsilah Baru</span></div></div></div></div>
    {sh&&<div className="modal-ov" onClick={()=>setSh(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="m-h"><h2>Silsilah Baru</h2><button className="btn btn-icon btn-ghost" onClick={()=>setSh(false)}><Ic.X/></button></div><div className="m-b"><div className="fg"><label className="fl">Nama Keluarga *</label><input className="fi" value={nn} onChange={e=>setNn(e.target.value)} placeholder="Keluarga Besar ..." autoFocus/></div><div className="fg"><label className="fl">Deskripsi</label><textarea className="fta" value={nd} onChange={e=>setNd(e.target.value)} placeholder="..."/></div></div><div className="m-f"><button className="btn" onClick={()=>setSh(false)}>Batal</button><button className="btn btn-p" onClick={cr} disabled={!nn.trim()}>Buat</button></div></div></div>}
  </div>)}
// ═══════════════════════════════════════════════════════════════
// WORKSPACE
// ═══════════════════════════════════════════════════════════════
function Workspace({family:initF,user,onBack}){const[fam,setFam]=useState(initF);const pp=fam.members||[];const[pos,setPos]=useState(fam.positions||{});const[vw,setVw]=useState(VW.CANVAS);const[search,setSearch]=useState("");const[sel,setSel]=useState(null);const[showForm,setShowForm]=useState(false);const[editP,setEditP]=useState(null);const[showShare,setShowShare]=useState(false);const[showIE,setShowIE]=useState(false);const[toast,setToast]=useState(null);const[filters,setFilters]=useState({});
  const myRole=(fam.collaborators||[]).find(c=>c.userId===user.id)?.role||RL.V;const canEdit=myRole!==RL.V;
  const flash=m=>{setToast(m);setTimeout(()=>setToast(null),3000)};
  const saveFam=async f=>{f.updatedAt=new Date().toISOString();await DB.setFamily(f);setFam({...f})};
  const setPP=fn=>{saveFam({...fam,members:typeof fn==="function"?fn(pp):fn})};
  const handleSave=(person,lsid,ltid)=>{if(!canEdit)return;if(lsid&&ltid){setPP(p=>p.map(x=>x.id===lsid?{...x,spouseId:ltid}:x));return}if(!person)return;setPP(prev=>{const ex=prev.find(x=>x.id===person.id);if(ex){flash(`${person.name} diperbarui`);return prev.map(x=>x.id===person.id?person:x)}flash(`${person.name} ditambahkan`);return[...prev,person]})};
  const handleDel=id=>{if(!canEdit)return;const p=pp.find(x=>x.id===id);if(FE.ch(pp,id).length){alert(`Tidak bisa hapus — ${p.name} masih punya anak.`);return}if(confirm(`Hapus ${p.name}?`)){setPP(prev=>prev.filter(x=>x.id!==id).map(x=>x.spouseId===id?{...x,spouseId:null}:x));setSel(null);flash(`${p.name} dihapus`)}};
  const loadDemo=()=>{if(confirm("Muat data demo Keluarga Syachroel?")){saveFam({...fam,members:SEED,positions:{}});setPos({});flash("Data demo dimuat!")}};
  const updPos=useCallback(p=>{setPos(p);saveFam({...fam,positions:p})},[fam]);
  const filtered=useMemo(()=>FE.search(pp,search),[pp,search]);const viewPP=search?filtered:pp;
  return(<div className="app"><header className="ws-h"><button className="btn btn-sm btn-ghost" onClick={onBack}><Ic.Back/></button><div className="ws-br"><h1>NAS<em>AB</em></h1><span style={{color:"var(--t3)",fontSize:11,margin:"0 3px"}}>/</span><span style={{fontSize:11,fontWeight:600}}>{fam.name}</span></div><span className="ws-tag">v{APP.ver}</span>
    <nav className="nav">{[{id:VW.CANVAS,l:"Canvas"},{id:VW.MAP,l:"Peta"},{id:VW.LIST,l:"Daftar"},{id:VW.STATS,l:"Stats"},{id:VW.TL,l:"Timeline"},{id:VW.INS,l:"Insights"},{id:VW.WARIS,l:"⚖️Waris"}].map(t=><button key={t.id} className={`navt ${vw===t.id?"on":""}`} onClick={()=>setVw(t.id)}>{t.l}</button>)}</nav>
    <div className="ws-act"><div className="sbox"><Ic.Search/><input placeholder="Cari..." value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="btn btn-sm" onClick={()=>setShowShare(true)}><Ic.Share/></button><button className="btn btn-sm" onClick={()=>setShowIE(true)}><Ic.DL/></button>{!pp.length&&<button className="btn btn-sm" onClick={loadDemo}>Demo</button>}{canEdit&&<button className="btn btn-p btn-sm" onClick={()=>{setEditP(null);setShowForm(true)}}><Ic.Plus/> Tambah</button>}</div></header>
    <div style={{flex:1,position:"relative",overflow:"hidden"}}>
      {vw===VW.CANVAS&&<CanvasView pp={viewPP} onSel={setSel} selId={sel?.id} onPos={updPos} savedPos={pos}/>}
      {vw===VW.MAP&&<MapView pp={viewPP} onSel={setSel}/>}
      {vw===VW.LIST&&<div style={{height:"100%",overflow:"auto"}}><div style={{maxWidth:760,margin:"0 auto",padding:"14px 14px 0"}}><FilterBar pp={pp} filters={filters} setFilters={setFilters}/></div><ListView pp={Object.keys(filters).length?FE.filter(viewPP,filters):viewPP} allPP={pp} onSel={setSel}/></div>}
      {vw===VW.STATS&&<div style={{height:"100%",overflow:"auto"}}><StatsView pp={viewPP}/></div>}
      {vw===VW.TL&&<div style={{height:"100%",overflow:"auto"}}><TimelineView pp={viewPP} onSel={setSel}/></div>}
      {vw===VW.INS&&<InsightsView pp={pp} fam={fam} canEdit={canEdit} onSave={saveFam} flash={flash}/>}
      {vw===VW.WARIS&&<div style={{height:"100%",overflow:"auto"}}><WarisView pp={pp}/></div>}
      {sel&&<Sidebar p={sel} pp={pp} canEdit={canEdit} onClose={()=>setSel(null)} onEdit={p=>{setSel(null);setEditP(p);setShowForm(true)}} onDel={handleDel} onSel={setSel}/>}
    </div>
    {showForm&&canEdit&&<PersonForm person={editP} pp={pp} onSave={handleSave} onClose={()=>{setShowForm(false);setEditP(null)}}/>}
    {showShare&&<ShareModal fam={fam} user={user} onClose={()=>setShowShare(false)} onUpd={saveFam} flash={flash}/>}
    {showIE&&<IEModal pp={pp} onImport={d=>{setPP(()=>d);setPos({});flash("Data diimport")}} onClose={()=>setShowIE(false)}/>}
    {toast&&<div className="toast">{toast}</div>}
  </div>)}
// ─── CANVAS (Drag & Drop + Auto-Connectors + Gen Lanes) ─────
function CanvasView({pp,onSel,selId,onPos,savedPos}){const wr=useRef(null);const[pos,setPos]=useState({});const[pan,setPan]=useState({x:0,y:0});const[zm,setZm]=useState(1);const[didInitFit,setDidInitFit]=useState(false);const[drag,setDrag]=useState(null);const[panning,setPanning]=useState(false);const[didD,setDidD]=useState(false);const ps=useRef({});const ds=useRef({});
  useEffect(()=>{if(savedPos&&Object.keys(savedPos).length>=pp.length)setPos(savedPos);else{const a=autoLayout(pp);setPos(a);onPos(a)}},[pp]);
  useEffect(()=>{if(Object.keys(pos).length>0)onPos(pos)},[pos]);
  const conns=useMemo(()=>getConns(pp,pos),[pp,pos]);
  const rootMap=useMemo(()=>{const m={};pp.forEach(p=>{let cur=p;const seen=new Set();while(cur&&cur.parentId&&!seen.has(cur.id)){seen.add(cur.id);const next=pp.find(x=>x.id===cur.parentId);if(!next)break;cur=next}m[p.id]=cur?.id||p.id});return m},[pp]);
  const branchIdx=useMemo(()=>{const idx={};const uniqueRoots=[...new Set(Object.values(rootMap))].sort();uniqueRoots.forEach((rid,i)=>{idx[rid]=i});return idx},[rootMap]);
  const bnd=useMemo(()=>{let mx=0,my=0;Object.values(pos).forEach(p=>{mx=Math.max(mx,p.x+CW+200);my=Math.max(my,p.y+CH+200)});return{w:Math.max(mx,2000),h:Math.max(my,1200)}},[pos]);
  const gls=useMemo(()=>{const l={};pp.forEach(p=>{const g=FE.gen(pp,p.id);const po=pos[p.id];if(!po)return;if(!l[g])l[g]={mi:po.y,mx:po.y+CH};l[g].mi=Math.min(l[g].mi,po.y);l[g].mx=Math.max(l[g].mx,po.y+CH)});return l},[pp,pos]);
  const onPS=e=>{if(e.target.closest('.cc')||e.target.closest('.zm')||e.target.closest('.mm'))return;setPanning(true);ps.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y}};
  useEffect(()=>{const mv=e=>{if(panning)setPan({x:ps.current.px+(e.clientX-ps.current.x),y:ps.current.py+(e.clientY-ps.current.y)});if(drag){const dx=(e.clientX-ds.current.x)/zm,dy=(e.clientY-ds.current.y)/zm;if(Math.abs(dx)>3||Math.abs(dy)>3)setDidD(true);setPos(prev=>({...prev,[drag]:{x:ds.current.ox+dx,y:ds.current.oy+dy}}))}};const up=()=>{setPanning(false);setDrag(null)};window.addEventListener("mousemove",mv);window.addEventListener("mouseup",up);return()=>{window.removeEventListener("mousemove",mv);window.removeEventListener("mouseup",up)}});
  useEffect(()=>{const el=wr.current;const wh=e=>{e.preventDefault();setZm(z=>Math.max(.1,Math.min(2.5,z+(e.deltaY>0?-.05:.05))))};if(el)el.addEventListener("wheel",wh,{passive:false});return()=>el&&el.removeEventListener("wheel",wh)},[]);
  const dS=(e,pid)=>{e.stopPropagation();setDrag(pid);setDidD(false);ds.current={x:e.clientX,y:e.clientY,ox:pos[pid].x,oy:pos[pid].y}};
  const cC=(e,p)=>{e.stopPropagation();if(!didD)onSel(p)};
  const fitToViewport=useCallback(()=>{if(!wr.current||!Object.keys(pos).length)return;const rect=wr.current.getBoundingClientRect();const viewW=rect.width-80,viewH=rect.height-80;let mnX=Infinity,mnY=Infinity,mxX=-Infinity,mxY=-Infinity;Object.values(pos).forEach(p=>{mnX=Math.min(mnX,p.x);mnY=Math.min(mnY,p.y);mxX=Math.max(mxX,p.x+CW);mxY=Math.max(mxY,p.y+CH)});if(!isFinite(mnX))return;const contentW=mxX-mnX,contentH=mxY-mnY;const targetZm=Math.min(viewW/contentW,viewH/contentH,1.2);const newZm=Math.max(0.3,targetZm);const cx=(mnX+mxX)/2,cy=(mnY+mxY)/2;setZm(newZm);setPan({x:rect.width/2-cx*newZm,y:rect.height/2-cy*newZm})},[pos]);
  useEffect(()=>{if(!didInitFit&&Object.keys(pos).length>0&&wr.current){const t=setTimeout(()=>{fitToViewport();setDidInitFit(true)},80);return()=>clearTimeout(t)}},[pos,didInitFit,fitToViewport]);
  const fit=()=>{const np=autoLayout(pp);setPos(np);setTimeout(()=>fitToViewport(),50)};
  if(!pp.length)return<div className="empty"><h3>Mulai dari sini</h3><p>Tambahkan anggota pertama atau muat data demo</p></div>;
  return(<div ref={wr} className={`cvs ${panning?"grabbing":""}`} onMouseDown={onPS}>
    <div className="cvs-in" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zm})`,width:bnd.w,height:bnd.h}}>
      {Object.entries(gls).map(([g,lane])=>{const gi=parseInt(g);const gl=GL[gi]||{l:`Gen ${gi+1}`};const c=GC[gi%GC.length];const minX=Math.min(...pp.filter(p=>FE.gen(pp,p.id)===gi).map(p=>pos[p.id]?.x??Infinity));return(<div key={g} className="gen-lane" style={{position:"absolute",left:Math.max(20,minX-160),top:lane.mi+CH/2-14,pointerEvents:"none",zIndex:1}}><div style={{background:`${c}15`,border:`1px solid ${c}40`,color:c,padding:"4px 12px",borderRadius:14,fontSize:11,fontWeight:600,fontFamily:"var(--fm)",letterSpacing:".4px",whiteSpace:"nowrap"}}>Gen {gi+1} · {gl.l}</div></div>)})}
      <svg className="conn-svg" width={bnd.w} height={bnd.h}>{conns.map((c,i)=>{if(c.t==="sp"){const mx=(c.x1+c.x2)/2;return(<g key={i}><line x1={c.x1} y1={c.y1} x2={c.x2} y2={c.y2} stroke="var(--rose)" strokeWidth="1.5" strokeDasharray="5,4" opacity=".55"/><circle cx={mx} cy={c.y1} r="9" fill="var(--bg1)" stroke="var(--rose)" strokeWidth="1"/><text x={mx} y={c.y1+1} textAnchor="middle" dominantBaseline="central" fontSize="13" fill="var(--rose)">∞</text></g>)}if(c.t==="pd"){return<path key={i} d={`M ${c.x1} ${c.y1} L ${c.x2} ${c.y2}`} fill="none" stroke="var(--t3)" strokeWidth="1.5" opacity=".9"/>}if(c.t==="br"){return<line key={i} x1={c.x1} y1={c.y1} x2={c.x2} y2={c.y2} stroke="var(--t3)" strokeWidth="1.5" opacity=".9"/>}if(c.t==="cd"){const dy=c.y2-c.y1;return<path key={i} d={`M ${c.x1} ${c.y1} C ${c.x1} ${c.y1+dy*0.5}, ${c.x2} ${c.y1+dy*0.5}, ${c.x2} ${c.y2}`} fill="none" stroke="var(--t3)" strokeWidth="1.75" opacity=".9"/>}return null})}</svg>
      {pp.map(p=>{const po=pos[p.id];if(!po)return null;const g=FE.gen(pp,p.id);const isDec=!!p.deathDate;const yr=p.birthDate?new Date(p.birthDate).getFullYear():null;const age=FE.age(p);const meta=[p.gender==="male"?"♂":"♀",yr?`${yr}`:null,age!==null?`${age} th`:null].filter(Boolean).join(" · ");return(<div key={p.id} className={`cc ${p.gender} b${branchIdx[rootMap[p.id]]%8} ${drag===p.id?"dragging":""} ${selId===p.id?"selected":""} ${isDec?"deceased":""}`} style={{left:po.x,top:po.y,width:CW,minHeight:CH}} onMouseDown={e=>dS(e,p.id)} onClick={e=>cC(e,p)}><span className="cc-badge-gen">G{g+1}</span>{p.nik&&<span className="cc-badge-nik">NIK</span>}<div className={`cc-av ${p.gender}`}>{ini(p.name)}</div><div className="cc-nm">{p.name}</div><div className="cc-mt">{meta}</div></div>)})}
    </div>
    <div className="zm"><button onClick={()=>setZm(z=>Math.min(2.5,z+.1))}>+</button><button onClick={()=>setZm(z=>Math.max(.1,z-.1))}>−</button><button onClick={fit}><Ic.Fit/></button><div style={{fontSize:7,textAlign:"center",color:"var(--t3)",fontFamily:"var(--fm)"}}>{Math.round(zm*100)}%</div></div>
    <div className="mm"><svg width="140" height="70" viewBox={`0 0 ${bnd.w} ${bnd.h}`}>{pp.map(p=>{const po=pos[p.id];return po?<rect key={p.id} x={po.x} y={po.y} width={CW} height={CH} rx="2" fill={p.gender==="male"?"var(--male-t)":"var(--fem-t)"} opacity=".3"/>:null})}</svg></div>
  </div>)}
// ─── MAP ─────────────────────────────────────────────────────
const LL={p:null};function loadL(){if(window.L)return Promise.resolve(window.L);if(LL.p)return LL.p;LL.p=new Promise(r=>{const s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js";s.onload=()=>r(window.L);document.head.appendChild(s)});return LL.p}
function MapView({pp,onSel}){const mr=useRef(null);const mi=useRef(null);const mk=useRef([]);const[rdy,setRdy]=useState(false);const[flt,setFlt]=useState("all");const geo=useMemo(()=>pp.filter(p=>p.location?.lat),[pp]);
  useEffect(()=>{loadL().then(L=>{if(!mr.current||mi.current)return;const m=L.map(mr.current,{zoomControl:false}).setView([-2.5,112],5);L.control.zoom({position:"topleft"}).addTo(m);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:19}).addTo(m);mi.current=m;setRdy(true)});return()=>{if(mi.current){mi.current.remove();mi.current=null}}},[]);
  useEffect(()=>{if(!rdy||!mi.current||!window.L)return;const L=window.L,m=mi.current;mk.current.forEach(x=>m.removeLayer(x));mk.current=[];const fl=flt==="all"?geo:geo.filter(p=>FE.gen(pp,p.id)===parseInt(flt.replace("g-","")));const bn=[];
    fl.forEach(p=>{const g=FE.gen(pp,p.id);const c=GC[g%GC.length];const ic=L.divIcon({className:"",html:`<div style="width:24px;height:24px;border-radius:5px;background:${c};display:flex;align-items:center;justify-content:center;font-size:8px;font-weight:700;color:#000;font-family:'DM Sans';box-shadow:0 2px 6px ${c}55;cursor:pointer">${ini(p.name)}</div>`,iconSize:[24,24],iconAnchor:[12,12]});const marker=L.marker([p.location.lat,p.location.lng],{icon:ic}).addTo(m);marker.bindPopup(`<div style="font-family:'DM Sans';min-width:140px"><div style="font-family:'Instrument Serif';font-size:13px;font-weight:700">${p.name}</div><div style="font-size:10px;color:#666">${p.gender==="male"?"♂":"♀"} · ${p.location.address||"—"}</div></div>`,{maxWidth:200});marker.on("click",()=>onSel(p));mk.current.push(marker);bn.push([p.location.lat,p.location.lng])});
    if(bn.length>1)m.fitBounds(bn,{padding:[35,35],maxZoom:14});else if(bn.length===1)m.setView(bn[0],13);
  },[rdy,geo,flt,pp]);const uG=useMemo(()=>[...new Set(geo.map(p=>FE.gen(pp,p.id)))].sort(),[geo,pp]);
  return(<div className="map-w"><div ref={mr} className="map-c"/><div className="map-leg"><div className="map-leg-t">LOKASI</div><div className="map-leg-i" style={{fontWeight:flt==="all"?700:400}} onClick={()=>setFlt("all")}><div className="map-leg-d" style={{background:"var(--t2)"}}/>Semua ({geo.length})</div>{uG.map(g=>{const gl=GL[g]||{l:`Gen ${g+1}`};const c=GC[g%GC.length];const a=flt===`g-${g}`;return<div key={g} className="map-leg-i" style={{fontWeight:a?700:400}} onClick={()=>setFlt(a?"all":`g-${g}`)}><div className="map-leg-d" style={{background:c}}/>{gl.l} ({geo.filter(p=>FE.gen(pp,p.id)===g).length})</div>})}</div><div className="map-bar"><div className="map-st">📍 <b>{geo.length}</b>/{pp.length}</div></div>{!geo.length&&<div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)",zIndex:1e3,textAlign:"center",background:"var(--bg1)",border:"1px solid var(--bdr)",borderRadius:"var(--r)",padding:"18px 24px"}}><div style={{fontSize:26}}>🗺️</div><div style={{fontSize:12,fontWeight:600,marginTop:3}}>Belum ada lokasi</div></div>}</div>)}
// ─── NIK INPUT ───────────────────────────────────────────────
function NikInput({value,onChange,onParsed}){const[v,setV]=useState(value||"");const[res,setRes]=useState(null);
  const handle=val=>{setV(val);onChange(val);const s=val.replace(/\D/g,"");if(s.length===16){const r=NIK.parse(s);setRes(r);if(r.valid&&onParsed)onParsed(r)}else setRes(null)};
  return(<div className="nik-box"><input placeholder="Masukkan 16 digit NIK" value={v} onChange={e=>handle(e.target.value)} maxLength={20}/>
    {res&&(res.valid?<div className="nik-result nik-ok">✓ Valid — {res.gender==="male"?"♂ Laki-laki":"♀ Perempuan"} · Lahir {res.day}/{res.month}/{res.year} · {res.provinsi} · Masked: {res.masked}</div>:<div className="nik-result nik-err">✕ {res.error}</div>)}
  </div>)}
// ─── GEO INPUT ───────────────────────────────────────────────
function GeoInput({value:v,onChange:oc}){const[q,setQ]=useState("");const[res,setRes]=useState([]);const[busy,setBusy]=useState(false);
  const doS=async()=>{if(!q.trim())return;setBusy(true);try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(q)}&limit=5&countrycodes=id`);const d=await r.json();setRes(d.map(x=>({lat:parseFloat(x.lat),lng:parseFloat(x.lon),address:x.display_name.split(",").slice(0,3).join(",").trim()})))}catch{}setBusy(false)};
  return(<div className="geo-w"><div className="geo-r"><input placeholder="Cari lokasi..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doS()}/><button className="btn btn-sm" onClick={doS} style={{padding:"2px 4px",fontSize:8}}>{busy?"…":"🔍"}</button></div>{res.length>0&&<div className="geo-res">{res.map((r,i)=><div key={i} className="geo-ri" onClick={()=>{oc(r);setRes([]);setQ("")}}>📍 {r.address}</div>)}</div>}<div className="geo-r"><span className="geo-l">Lat</span><input type="number" step="any" value={v?.lat||""} onChange={e=>oc({lat:parseFloat(e.target.value)||0,lng:v?.lng||0,address:v?.address||""})}/><span className="geo-l">Lng</span><input type="number" step="any" value={v?.lng||""} onChange={e=>oc({lat:v?.lat||0,lng:parseFloat(e.target.value)||0,address:v?.address||""})}/></div><div className="geo-r"><span className="geo-l">Alamat</span><input value={v?.address||""} onChange={e=>oc({lat:v?.lat||0,lng:v?.lng||0,address:e.target.value})}/></div>{v?.lat&&<div style={{display:"flex",gap:3,marginTop:2}}><button className="btn btn-sm btn-d" onClick={()=>oc(null)} style={{fontSize:7,padding:"1px 4px"}}>✕</button><span style={{fontSize:7,color:"var(--pri)"}}>✓ Saved</span></div>}</div>)}
// ─── PERSON FORM (with NIK Intelligence) ─────────────────────
function PersonForm({person:p,pp,onSave,onClose}){const ie=!!p?.id;
  const[f,sF]=useState({name:p?.name||"",gender:p?.gender||"male",birthDate:p?.birthDate||"",deathDate:p?.deathDate||"",birthPlace:p?.birthPlace||"",notes:p?.notes||"",parentId:p?.parentId||"",spouseId:p?.spouseId||"",location:p?.location||null,nik:p?.nik||""});
  const set=(k,v)=>sF(x=>({...x,[k]:v}));
  const onNikParsed=(r)=>{
    // Auto-fill from NIK
    const updates={};
    if(r.gender)updates.gender=r.gender;
    if(r.birthDate&&!f.birthDate)updates.birthDate=r.birthDate;
    if(r.provinsi&&!f.birthPlace)updates.birthPlace=r.provinsi;
    if(r.coords&&!f.location)updates.location={lat:r.coords[0],lng:r.coords[1],address:r.provinsi};
    sF(x=>({...x,...updates}));
  };
  const save=()=>{if(!f.name.trim())return;const d={...f,parentId:f.parentId||null,spouseId:f.spouseId||null};if(ie)onSave({...p,...d});else onSave({id:`p_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,...d,photo:"",createdAt:new Date().toISOString()});if(f.spouseId)onSave(null,f.spouseId,ie?p.id:null);onClose()};
  return(<div className="modal-ov" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()} style={{maxWidth:480}}>
    <div className="m-h"><h2>{ie?"Edit":"Tambah"}</h2><button className="btn btn-icon btn-ghost" onClick={onClose}><Ic.X/></button></div>
    <div className="m-b">
      <div className="fg"><label className="fl">🆔 NIK (auto-fill gender, lahir, lokasi)</label><NikInput value={f.nik} onChange={v=>set("nik",v)} onParsed={onNikParsed}/></div>
      <div className="fg"><label className="fl">Nama *</label><input className="fi" value={f.name} onChange={e=>set("name",e.target.value)} autoFocus placeholder="Nama lengkap"/></div>
      <div className="fg"><label className="fl">Gender</label><div className="gtog"><button className={`gbtn ${f.gender==="male"?"am":""}`} onClick={()=>set("gender","male")}>♂ L</button><button className={`gbtn ${f.gender==="female"?"af":""}`} onClick={()=>set("gender","female")}>♀ P</button></div></div>
      <div className="fr"><div className="fg"><label className="fl">Lahir</label><input className="fi" type="date" value={f.birthDate} onChange={e=>set("birthDate",e.target.value)}/></div><div className="fg"><label className="fl">Wafat</label><input className="fi" type="date" value={f.deathDate} onChange={e=>set("deathDate",e.target.value)}/></div></div>
      <div className="fg"><label className="fl">Tempat Lahir</label><input className="fi" value={f.birthPlace} onChange={e=>set("birthPlace",e.target.value)}/></div>
      <div className="fr"><div className="fg"><label className="fl">Orang Tua</label><select className="fsel" value={f.parentId} onChange={e=>set("parentId",e.target.value)}><option value="">— Root —</option>{pp.filter(x=>!ie||x.id!==p?.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="fg"><label className="fl">Pasangan</label><select className="fsel" value={f.spouseId} onChange={e=>set("spouseId",e.target.value)}><option value="">—</option>{pp.filter(x=>(!ie||x.id!==p?.id)&&!x.spouseId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div>
      <div className="fg"><label className="fl">Catatan</label><textarea className="fta" value={f.notes} onChange={e=>set("notes",e.target.value)}/></div>
      <div className="fg"><label className="fl">📍 Lokasi</label><GeoInput value={f.location} onChange={v=>set("location",v)}/></div>
    </div>
    <div className="m-f"><button className="btn" onClick={onClose}>Batal</button><button className="btn btn-p" onClick={save} disabled={!f.name.trim()}>{ie?"Simpan":"Tambah"}</button></div>
  </div></div>)}
// ─── SHARE ───────────────────────────────────────────────────
function ShareModal({fam,user,onClose,onUpd,flash}){const[em,setEm]=useState("");const[rl,setRl]=useState(RL.E);const inv=async()=>{if(!em.trim())return;const u=await DB.getUserByEmail(em);if(u){if((fam.collaborators||[]).find(c=>c.userId===u.id)){flash("Sudah bergabung");return}onUpd({...fam,collaborators:[...(fam.collaborators||[]),{userId:u.id,name:u.name,role:rl}]});flash(`${u.name} diundang`)}else{onUpd({...fam,invites:[...(fam.invites||[]),{email:em.toLowerCase(),role:rl,by:user.name}]});flash(`Undangan ke ${em}`)}setEm("")};
  return(<div className="modal-ov" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()} style={{maxWidth:400}}><div className="m-h"><h2>Kolaborasi</h2><button className="btn btn-icon btn-ghost" onClick={onClose}><Ic.X/></button></div><div style={{padding:12}}>
    <div style={{display:"flex",gap:4,marginBottom:12}}><input className="fi" style={{flex:1,padding:"4px 7px",fontSize:10}} value={em} onChange={e=>setEm(e.target.value)} placeholder="email@..." onKeyDown={e=>e.key==="Enter"&&inv()}/><select className="fsel" style={{width:70,padding:"4px",fontSize:9}} value={rl} onChange={e=>setRl(e.target.value)}><option value={RL.E}>Editor</option><option value={RL.V}>Viewer</option></select><button className="btn btn-p btn-sm" onClick={inv}>Undang</button></div>
    <div style={{fontSize:9,color:"var(--t3)",marginBottom:6}}>Tim ({(fam.collaborators||[]).length})</div>
    {(fam.collaborators||[]).map((c,i)=><div key={i} className="collab-i"><div className="collab-av">{ini(c.name)}</div><div className="collab-info">{c.name}{c.userId===user.id&&<span>(Anda)</span>}</div><span className="collab-rl" style={{background:c.role===RL.O?"var(--pri)":"var(--acc)",color:c.role===RL.O?"#000":"#fff"}}>{c.role}</span></div>)}
    <div style={{marginTop:10,padding:"6px 8px",background:"var(--bg2)",borderRadius:5,fontSize:8,color:"var(--t3)",fontFamily:"var(--fm)"}}>OWNER=full · EDITOR=edit · VIEWER=view only</div>
  </div></div></div>)}
// ─── WARIS (FARAIDH) ─────────────────────────────────────────
function WarisView({pp}){const[did,setDid]=useState("");const[th,setTh]=useState("");const[ht,setHt]=useState("");const[ws,setWs]=useState("");const[res,setRes]=useState(null);
  const calc=()=>{if(!did||!th)return;setRes(FE.faraidh.calc(pp,did,parseFloat(th)||0,parseFloat(ht)||0,parseFloat(ws)||0))};
  const fmt=n=>new Intl.NumberFormat("id-ID").format(n);const clrs=["#14b8a6","#6366f1","#f59e0b","#ec4899","#8b5cf6","#f97316","#06b6d4","#84cc16"];
  const heirs=did?FE.faraidh.getHeirs(pp,did):[];
  return(<div className="wr"><div className="wr-hd"><h2>⚖️ Kalkulator <em>Faraidh</em></h2><p>Pembagian waris sesuai hukum Islam — An-Nisa:11-12 & KHI</p></div>
    <div className="wr-form"><div className="wr-ig wr-ff"><label>PEWARIS</label><select value={did} onChange={e=>{setDid(e.target.value);setRes(null)}}><option value="">— Pilih pewaris —</option>{pp.map(p=><option key={p.id} value={p.id}>{p.name} ({p.gender==="male"?"♂":"♀"})</option>)}</select></div>
      <div className="wr-ig"><label>TOTAL HARTA (RP)</label><input type="number" placeholder="1.000.000.000" value={th} onChange={e=>setTh(e.target.value)}/></div>
      <div className="wr-ig"><label>HUTANG (RP)</label><input type="number" placeholder="0" value={ht} onChange={e=>setHt(e.target.value)}/></div>
      <div className="wr-ig"><label>WASIAT (RP, MAKS ⅓)</label><input type="number" placeholder="0" value={ws} onChange={e=>setWs(e.target.value)}/></div>
      <div className="wr-ig"><button className="btn btn-p btn-block" onClick={calc} disabled={!did||!th}>⚖️ Hitung</button></div>
    </div>
    {did&&!res&&heirs.length>0&&<div style={{background:"var(--bg2)",border:"1px solid var(--bdr)",borderRadius:"var(--r)",padding:10,marginBottom:10}}><div style={{fontSize:10,fontWeight:600,marginBottom:4}}>Ahli Waris ({heirs.length}):</div>{heirs.map((h,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:5,padding:"3px 0",fontSize:10}}><span style={{color:h.gender==="male"?"var(--male-t)":"var(--fem-t)"}}>{h.gender==="male"?"♂":"♀"}</span><b>{h.name}</b><span style={{fontSize:7,color:"var(--t3)",fontFamily:"var(--fm)",background:"var(--bg3)",padding:"1px 4px",borderRadius:2}}>{h.relation.replace(/_/g," ")}</span></div>)}</div>}
    {res&&!res.error&&<div className="wr-res"><div className="wr-rh"><h3>Hasil — {res.pewaris.name}</h3><p>{res.shares.length} ahli waris</p></div>
      <div className="wr-ded"><div className="wr-dd">Harta <b>Rp {fmt(res.totalHarta)}</b></div>{res.hutang>0&&<div className="wr-dd">−Hutang <b>Rp {fmt(res.hutang)}</b></div>}{res.wasiat>0&&<div className="wr-dd">−Wasiat <b>Rp {fmt(res.wasiat)}</b></div>}<div className="wr-dd" style={{background:"rgba(20,184,166,.08)",color:"var(--pri)"}}>= <b>Rp {fmt(res.hartaWarisan)}</b></div></div>
      <div style={{padding:"8px 14px"}}><div style={{display:"flex",borderRadius:6,overflow:"hidden",height:12}}>{res.shares.map((s,i)=><div key={i} style={{width:`${s.pct}%`,background:clrs[i%clrs.length],minWidth:s.pct>0?2:0}} title={`${s.person.name}: ${s.pct}%`}/>)}</div></div>
      <div>{res.shares.map((s,i)=><div key={i} className="wr-sr"><div className={`wr-sr-av ${s.person.gender}`}>{ini(s.person.name)}</div><div className="wr-sr-info"><div className="wr-sr-nm">{s.person.name}</div><div className="wr-sr-rl">{s.relation} · {s.type==="furudh"?"Furudh":"Ashabah"}</div></div><span className="wr-sr-bs">{s.basis}</span><span className="wr-sr-pct" style={{color:clrs[i%clrs.length]}}>{s.pct}%</span><span className="wr-sr-amt">Rp {fmt(s.amt)}</span></div>)}</div>
      <div className="wr-dis">⚠️ Simulasi berdasarkan An-Nisa:11-12 & KHI 176-191. Untuk kasus kompleks konsultasikan ulama/PA.</div>
    </div>}
    {res?.error&&<div style={{padding:16,textAlign:"center",background:"var(--bg2)",border:"1px solid var(--bdr)",borderRadius:"var(--r)"}}><span style={{fontSize:24}}>⚠️</span><div style={{fontSize:12,fontWeight:600,marginTop:4}}>{res.error}</div></div>}
    <div style={{marginTop:12,background:"var(--bg2)",border:"1px solid var(--bdr)",borderRadius:"var(--r)",padding:10}}><div style={{fontSize:10,fontFamily:"var(--fd)",fontWeight:600,marginBottom:4}}>📚 Referensi Furudh</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:3,fontSize:8,color:"var(--t2)"}}><div><b style={{color:"var(--t1)"}}>Suami:</b> ½/¼</div><div><b style={{color:"var(--t1)"}}>Istri:</b> ¼/⅛</div><div><b style={{color:"var(--t1)"}}>Ayah:</b> ⅙/Ashabah</div><div><b style={{color:"var(--t1)"}}>Ibu:</b> ⅓/⅙</div><div><b style={{color:"var(--t1)"}}>1 Anak♀:</b> ½ / ≥2: ⅔</div><div><b style={{color:"var(--t1)"}}>Anak♂♀:</b> 2:1</div></div></div>
  </div>)}
// ─── INSIGHTS ────────────────────────────────────────────────
function InsightsView({pp,fam,canEdit,onSave,flash}){const[fid,setFid]=useState("");const[tid,setTid]=useState("");const[rr,setRr]=useState(null);const[st,setSt]=useState("");const[sp,setSp]=useState("");const stories=fam.stories||[];
  const bds=useMemo(()=>FE.bdays(pp,90),[pp]);const gd=useMemo(()=>{const d={};pp.forEach(p=>{const g=FE.gen(pp,p.id);d[g]=(d[g]||0)+1});return Object.entries(d).sort((a,b)=>a[0]-b[0]).map(([g,c])=>({gen:parseInt(g),count:c,label:(GL[parseInt(g)]||{l:`Gen ${parseInt(g)+1}`}).l,color:GC[parseInt(g)%GC.length]}))},[pp]);
  const ld=useMemo(()=>{const d={};pp.filter(p=>p.location?.address).forEach(p=>{const c=p.location.address.split(",")[0].trim();d[c]=(d[c]||0)+1});return Object.entries(d).sort((a,b)=>b[1]-a[1]).slice(0,6)},[pp]);
  const addS=()=>{if(!st.trim())return;onSave({...fam,stories:[{id:`s_${Date.now()}`,text:st,personId:sp||null,personName:sp?(pp.find(p=>p.id===sp)?.name||""):"",author:"Anda",date:new Date().toISOString()},...stories]});setSt("");flash("Cerita disimpan!")};
  return(<div className="ins"><h2 style={{fontFamily:"var(--fd)",fontSize:18,marginBottom:12}}>Insights</h2><div className="ins-g">
    <div className="ins-c"><h3><span>🔍</span>Pencari Hubungan</h3><div style={{display:"flex",gap:5,marginBottom:8,flexWrap:"wrap"}}><select className="fsel" style={{flex:1,fontSize:10}} value={fid} onChange={e=>setFid(e.target.value)}><option value="">Orang 1...</option>{pp.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="fsel" style={{flex:1,fontSize:10}} value={tid} onChange={e=>setTid(e.target.value)}><option value="">Orang 2...</option>{pp.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn btn-p btn-sm" onClick={()=>{if(fid&&tid)setRr(FE.findRel(pp,fid,tid))}} disabled={!fid||!tid}>Cari</button></div>{rr&&<div style={{background:"var(--bg3)",borderRadius:5,padding:"8px 10px",textAlign:"center"}}><div style={{fontFamily:"var(--fd)",fontSize:16,color:rr.path.length?"var(--pri)":"var(--t3)"}}>{rr.label}</div>{rr.path.length>0&&<div style={{fontSize:8,color:"var(--t3)",marginTop:4,display:"flex",alignItems:"center",justifyContent:"center",gap:3,flexWrap:"wrap"}}><span style={{background:"var(--bg2)",padding:"1px 5px",borderRadius:8,fontSize:8}}>{pp.find(p=>p.id===fid)?.name}</span>{rr.path.map((s,i)=><span key={i} style={{display:"flex",alignItems:"center",gap:2}}><span style={{color:"var(--pri)"}}>→</span><span style={{background:"var(--bg2)",padding:"1px 5px",borderRadius:8,fontSize:8}}>{pp.find(p=>p.id===s.id)?.name}</span></span>)}</div>}</div>}</div>
    <div className="ins-c"><h3><span>🎂</span>Ulang Tahun</h3>{!bds.length?<div style={{fontSize:10,color:"var(--t3)",textAlign:"center",padding:10}}>Tidak ada data</div>:bds.slice(0,5).map((b,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:6,padding:"4px 6px",background:"var(--bg3)",borderRadius:4,marginBottom:3}}><div style={{minWidth:38,textAlign:"center",fontSize:8,fontWeight:700,borderRadius:3,padding:"2px 4px",fontFamily:"var(--fm)",background:b.days===0?"var(--pri)":b.days<=7?"rgba(236,72,153,.12)":"var(--bg2)",color:b.days===0?"#000":b.days<=7?"var(--rose)":"var(--t2)"}}>{b.days===0?"TODAY":b.days+"d"}</div><div style={{flex:1,fontSize:10}}>{b.person.name} <span style={{color:"var(--t3)",fontSize:8}}>ke-{b.age}</span></div></div>)}</div>
    <div className="ins-c"><h3><span>📊</span>Distribusi</h3><div style={{display:"flex",borderRadius:16,overflow:"hidden",height:7,marginBottom:5}}>{gd.map(g=><div key={g.gen} style={{width:`${(g.count/pp.length)*100}%`,background:g.color}}/>)}</div><div style={{display:"flex",flexWrap:"wrap",gap:5,fontSize:8,color:"var(--t2)"}}>{gd.map(g=><div key={g.gen} style={{display:"flex",alignItems:"center",gap:2}}><div style={{width:5,height:5,borderRadius:"50%",background:g.color}}/>{g.label} ({g.count})</div>)}</div>{ld.length>0&&<div style={{marginTop:8}}>{ld.map(([city,ct],i)=><div key={i} style={{display:"flex",alignItems:"center",gap:5,marginBottom:3}}><span style={{fontSize:9,flex:1}}>{city}</span><div style={{width:60,height:4,background:"var(--bg3)",borderRadius:2,overflow:"hidden"}}><div style={{width:`${(ct/pp.length)*100}%`,height:"100%",background:"var(--pri)",borderRadius:2}}/></div><span style={{fontSize:8,color:"var(--t3)",fontFamily:"var(--fm)"}}>{ct}</span></div>)}</div>}</div>
    <div className="ins-c"><h3><span>⚡</span>Fakta</h3>{(()=>{const s=FE.stats(pp);const mc=pp.reduce((b,p)=>{const c=FE.ch(pp,p.id).length;return c>b.c?{p,c}:b},{p:null,c:0});return<div style={{fontSize:10,lineHeight:1.8,color:"var(--t2)"}}>{pp.length?`${((s.males/pp.length)*100).toFixed(0)}% ♂`:""} · {s.geotagged} geotagged · {s.nikCount} NIK<br/>{mc.p&&<>🏆 {mc.p.name}: {mc.c} anak</>} · {ld.length} kota</div>})()}</div>
    <div className="ins-c ins-cf"><h3><span>📖</span>Cerita Keluarga</h3>{canEdit&&<div style={{marginBottom:8}}><div style={{display:"flex",gap:4,marginBottom:4}}><select className="fsel" value={sp} onChange={e=>setSp(e.target.value)} style={{width:140,fontSize:9}}><option value="">Umum</option>{pp.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn btn-p btn-sm" onClick={addS} disabled={!st.trim()}>Simpan</button></div><textarea className="fta" value={st} onChange={e=>setSt(e.target.value)} placeholder="Tulis cerita keluarga..." style={{minHeight:36}}/></div>}{!stories.length?<div style={{fontSize:10,color:"var(--t3)",textAlign:"center",padding:14}}>Belum ada cerita</div>:stories.map(s=><div key={s.id} style={{background:"var(--bg3)",borderRadius:4,padding:"7px 9px",marginBottom:4}}><div style={{fontSize:7,color:"var(--t3)",fontFamily:"var(--fm)"}}>{new Date(s.date).toLocaleDateString("id-ID",{year:"numeric",month:"short",day:"numeric"})}{s.personName&&` · ${s.personName}`}</div><div style={{fontSize:10,lineHeight:1.4,color:"var(--t2)",marginTop:2}}>{s.text}</div><div style={{fontSize:7,color:"var(--pri)",marginTop:2}}>— {s.author}</div></div>)}</div>
  </div></div>)}
// ─── SIDEBAR ─────────────────────────────────────────────────
function Sidebar({p,pp,canEdit,onClose,onEdit,onDel,onSel}){const pa=FE.pa(pp,p);const sp=FE.sp(pp,p);const ch=FE.ch(pp,p.id);const sib=FE.sib(pp,p);const g=FE.gen(pp,p.id);const d=FE.desc(pp,p.id);const gl=GL[g]||{l:`Gen ${g+1}`};const age=FE.age(p);
  const ctx=useMemo(()=>{const c=[];if(pa)c.push(`Anak ${pa.name}`);if(sp)c.push(`∞ ${sp.name}`);if(ch.length)c.push(`${ch.length} anak`);return c.join(" · ")},[pa,sp,ch]);
  return(<div className="sb" onClick={e=>e.stopPropagation()}><div className="sb-h"><h3>Detail</h3><button className="btn btn-icon btn-ghost" onClick={onClose}><Ic.X/></button></div><div className="sb-b"><div className={`sb-av ${p.gender}`}>{ini(p.name)}</div><div className="sb-nm">{p.name}</div><div className="sb-sub">{p.gender==="male"?"♂":"♀"} · {gl.l}{p.deathDate?" · Alm.":""}</div>{ctx&&<div className="sb-ctx">{ctx}</div>}
    <div className="sb-sec"><div className="sb-sec-t">INFO</div>
      {p.nik&&<div className="sb-row"><span className="sb-row-l">🆔 NIK</span><span className="sb-row-v" style={{fontFamily:"var(--fm)",fontSize:9}}>{NIK.mask(p.nik)}</span></div>}
      {p.birthDate&&<div className="sb-row"><span className="sb-row-l">Lahir</span><span className="sb-row-v">{new Date(p.birthDate).toLocaleDateString("id-ID",{year:"numeric",month:"long",day:"numeric"})}</span></div>}
      {age!==null&&<div className="sb-row"><span className="sb-row-l">Usia</span><span className="sb-row-v">{age} th</span></div>}
      {p.birthPlace&&<div className="sb-row"><span className="sb-row-l">Tempat</span><span className="sb-row-v">{p.birthPlace}</span></div>}
      {p.location?.lat&&<div className="sb-row"><span className="sb-row-l">📍</span><span className="sb-row-v">{p.location.address}</span></div>}
      <div className="sb-row"><span className="sb-row-l">Keturunan</span><span className="sb-row-v">{d}</span></div>
      {p.notes&&<div className="sb-row"><span className="sb-row-l">Catatan</span><span className="sb-row-v">{p.notes}</span></div>}
    </div>
    <div className="sb-sec"><div className="sb-sec-t">HUBUNGAN</div>
      {pa&&<div className="sb-rel" onClick={()=>{onClose();setTimeout(()=>onSel(pa),50)}}><span className="sb-rel-t">PARENT</span>{pa.name}</div>}
      {sp&&<div className="sb-rel" onClick={()=>{onClose();setTimeout(()=>onSel(sp),50)}}><span className="sb-rel-t" style={{color:"var(--rose)"}}>SPOUSE</span>{sp.name}</div>}
      {sib.map(s=><div key={s.id} className="sb-rel" onClick={()=>{onClose();setTimeout(()=>onSel(s),50)}}><span className="sb-rel-t" style={{color:"var(--purple)"}}>SIBLING</span>{s.name}</div>)}
      {ch.map(c=><div key={c.id} className="sb-rel" onClick={()=>{onClose();setTimeout(()=>onSel(c),50)}}><span className="sb-rel-t" style={{color:"var(--pri)"}}>CHILD</span>{c.name}</div>)}
    </div></div>
    {canEdit&&<div className="sb-ft"><button className="btn btn-d btn-sm" onClick={()=>onDel(p.id)}><Ic.Trash/></button><button className="btn btn-p btn-sm" onClick={()=>onEdit(p)}><Ic.Edit/> Edit</button></div>}
  </div>)}
// ─── LIST/STATS/TIMELINE/FILTER/IE ───────────────────────────
function FilterBar({pp,filters:f,setFilters:sF}){const gs=useMemo(()=>[...new Set(pp.map(p=>FE.gen(pp,p.id)))].sort(),[pp]);const ls=useMemo(()=>[...new Set(pp.filter(p=>p.location?.address).map(p=>p.location.address.split(",")[0].trim()))].sort(),[pp]);const active=Object.values(f).some(v=>v&&v!=="all");
  return(<div className="fbar"><label>Gender<select value={f.gender||"all"} onChange={e=>sF(x=>({...x,gender:e.target.value}))}><option value="all">Semua</option><option value="male">♂</option><option value="female">♀</option></select></label><label>Generasi<select value={f.generation??"all"} onChange={e=>sF(x=>({...x,generation:e.target.value}))}><option value="all">Semua</option>{gs.map(g=><option key={g} value={g}>{(GL[g]||{l:`Gen ${g+1}`}).l}</option>)}</select></label><label>Status<select value={f.status||"all"} onChange={e=>sF(x=>({...x,status:e.target.value}))}><option value="all">Semua</option><option value="living">Hidup</option><option value="deceased">Almarhum</option></select></label><label>Lokasi<select value={f.location||""} onChange={e=>sF(x=>({...x,location:e.target.value}))}><option value="">Semua</option>{ls.map(l=><option key={l} value={l}>{l}</option>)}</select></label><label>NIK<select value={f.hasNik||"all"} onChange={e=>sF(x=>({...x,hasNik:e.target.value}))}><option value="all">Semua</option><option value="yes">Ada NIK</option><option value="no">Tanpa NIK</option></select></label>{active&&<span className="ftag" onClick={()=>sF({})}>✕ Reset</span>}</div>)}
function ListView({pp,allPP,onSel}){const people=allPP||pp;return(<div className="lv">{[...pp].sort((a,b)=>FE.gen(people,a.id)-FE.gen(people,b.id)||a.name.localeCompare(b.name)).map(p=>{const g=FE.gen(people,p.id);const gl=GL[g]||{l:`Gen ${g+1}`};const c=GC[g%GC.length];return<div key={p.id} className="li" onClick={()=>onSel(p)}><div className={`li-av ${p.gender}`}>{ini(p.name)}</div><div className="li-info"><h4>{p.name}{p.nik?" 🆔":""}</h4><p>{p.location?.address||p.notes||"—"}</p></div><span className="li-badge" style={{background:c+"15",color:c,border:`1px solid ${c}25`}}>{gl.l}</span></div>})}</div>)}
function StatsView({pp}){const s=useMemo(()=>FE.stats(pp),[pp]);return<div className="sg">{[{l:"Total",v:s.total,c:"var(--pri)"},{l:"Laki-laki",v:s.males,c:"var(--male-t)"},{l:"Perempuan",v:s.females,c:"var(--fem-t)"},{l:"Hidup",v:s.living,c:"var(--pri)"},{l:"Almarhum",v:s.deceased,c:"var(--t3)"},{l:"Generasi",v:s.generations,c:"var(--warn)"},{l:"Geotagged",v:s.geotagged,c:"var(--orange)"},{l:"NIK",v:s.nikCount,c:"var(--acc)"},{l:"Avg Anak",v:s.avgChildren,c:"var(--purple)"}].map((c,i)=><div key={i} className="sc"><div className="sc-v" style={{color:c.c}}>{c.v}</div><div className="sc-l">{c.l}</div></div>)}</div>}
function TimelineView({pp,onSel}){const ev=useMemo(()=>{const e=[];pp.forEach(p=>{if(p.birthDate)e.push({d:p.birthDate,t:"b",p,l:`Lahir: ${p.name}`});if(p.deathDate)e.push({d:p.deathDate,t:"d",p,l:`Wafat: ${p.name}`})});return e.sort((a,b)=>a.d.localeCompare(b.d))},[pp]);if(!ev.length)return<div className="empty"><h3>Belum ada peristiwa</h3><p>Tambahkan tanggal lahir/wafat</p></div>;return<div className="tl">{ev.map((e,i)=><div key={i} className="tl-i" onClick={()=>onSel(e.p)}><div className="tl-dot" style={{background:e.t==="b"?"var(--pri)":"var(--t3)"}}/><div className="tl-yr">{new Date(e.d).toLocaleDateString("id-ID",{year:"numeric",month:"long",day:"numeric"})}</div><div className="tl-tt">{e.l}</div></div>)}</div>}
function IEModal({pp,onImport,onClose}){const[j,setJ]=useState("");const[t,setT]=useState("e");return<div className="modal-ov" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="m-h"><h2>Data</h2><button className="btn btn-icon btn-ghost" onClick={onClose}><Ic.X/></button></div><div className="m-b"><div style={{display:"flex",gap:4,marginBottom:8}}><button className={`btn btn-sm ${t==="e"?"btn-p":""}`} onClick={()=>setT("e")}>Export</button><button className={`btn btn-sm ${t==="i"?"btn-p":""}`} onClick={()=>setT("i")}>Import</button></div>{t==="e"?<textarea className="fta" style={{minHeight:140,fontFamily:"var(--fm)",fontSize:8}} readOnly value={JSON.stringify(pp,null,2)}/>:<><textarea className="fta" style={{minHeight:140,fontFamily:"var(--fm)",fontSize:8}} value={j} onChange={e=>setJ(e.target.value)} placeholder="Paste JSON..."/><button className="btn btn-p btn-sm" style={{marginTop:4}} onClick={()=>{try{const d=JSON.parse(j);if(Array.isArray(d)){onImport(d);onClose()}}catch{alert("Invalid JSON")}}}>Import</button></>}</div></div></div>}
// ═══════════════════════════════════════════════════════════════
// APP
// ═══════════════════════════════════════════════════════════════
export default function App(){const[user,setUser]=useState(null);const[af,setAf]=useState(null);const[loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const s=await DB.g("session");if(s?.userId){const u=await DB.getUser(s.userId);if(u)setUser(u)}setLoading(false)})()},[]);
  const login=async u=>{setUser(u);await DB.s("session",{userId:u.id})};const logout=async()=>{setUser(null);setAf(null);await DB.d("session")};
  if(loading)return<div style={{height:"100vh",display:"flex",alignItems:"center",justifyContent:"center",background:"var(--bg0)",fontFamily:"var(--fd)",fontSize:18,color:"var(--t3)"}}>Loading...</div>;
  return<><style>{css}</style>{!user?<AuthScreen onLogin={login}/>:af?<Workspace family={af} user={user} onBack={()=>setAf(null)}/>:<Dashboard user={user} onLogout={logout} onSelect={f=>setAf(f)} onCreate={(u,f)=>{setUser(u);setAf(f)}}/>}</>;
}
